---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(readr)
```
```{r}
DF<-read_csv(("Proyecto_EyP.csv"))
```
```{r}
summary(DF)
```
```{r}
DF %>% rename (Temp=`Marca temporal`) -> DF1
```

```{r}
DF2 <- select(DF1,-Temp)
```
```{r}
summary(DF2)
```


```{r}
DF2 %>% rename (Correo=`Nombre de usuario`,Genero=`Genero con el que se identifica`,Años_Jugando= `¿Cuántos años llevas jugando videojuegos, aproximadamente? \n(puedes dar un numero decimal, y denotarlo con un punto, ejemplo: 12.5)`, Genero_favorito=`Tipo de juego favorito`, Elemento_favorito=`¿Qué elementos del juego son los que más te atrae?`,Horas_libres_semanales=`¿Cuantas horas libres tienes a la semana?`,Horas_de_juego_semanales=`De esas horas libres. ¿Cuántas horas juegas a la semana aproximadamente?`, Personas_con_quien_juega = `¿Con cuántas personas mayormente juegas? (en el caso de jugar en solitario, colocar un cero)`,Dispositivo=`Tipo de dispositivo en el que juegas mayormente`,Dinero_gastado=`¿Cuanto dinero gastas en los juegos por cada 3 meses? (solo colocar el dato numerico, sin ningun simbolo, y en valor de soles, si es decimal, colocar un punto para denotarlo)\nEn el caso de no gastar nada, solo colocar un cero.`, Semanas_pase_de_batalla=`¿Cuantas semanas crees que deberia de durar un pase de batalla (o un sistema de premios de intervalos de tiempo)?`,Meses_actualizacion=`¿Cada cuantos meses crees que un juego debería de actualizarse? (Esto para introducir nuevos personajes, historias spin-off, Lore, Armas, etc)\nSi quieres agregar semanas, agrega 0.25. ejemplo: 2 meses y 1 semana: 2.25\nEn el caso que prefieras que el juego sea estático (con una sola historia) entonces coloca cero`, Metodo_de_enterarse=`Cómo te enteras principalmente de un juego`) -> DFN3
```

```{r}
summary (DFN3)
```
```{r}
unique(DFN3$Genero_favorito)
```
```{r}
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("Estilo Anime (Fate/Grand Order, Honkai Impact, Genshin Impact, Tower of Fantasy, etc.)")] <- "Anime"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("Estrategia (Clash of Clans, Clash Royale, Civilization, etc.)")] <- "Estrategia"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("Battle Royale (COD Warzone, Apex Legends, PUBG , Fornite, Free fire, COD mobile, etc)")] <- "Battle_Royale"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("Accion (Devil May Cry 5, Nier Automata, Resident Evil, etc.)")] <- "Accion"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("Fps como valorant","FPS","FPS (Valorant, CSGO)","Wolfteam","FPS (Valorant, CSGO, Overwatch)","Shooters (Overwatch)","Historia (Resident evil, call of duty)","Shooter (Gears of War, Max Payne)","Hi-Life" )] <- "Shooter" #Se incluyen los FPS en los shooters, ya que estos son un subgénero
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("Rol por turnos (Dragon Quest IV, Fallout, X-com, etc)","Hogwarts Mystery")] <- "Rol"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("SandBox (Minecraft, Roblox, etc.)")] <- "Sandbox"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("FPS y MOBA","Fortnite, Full Guys, GtA V, Minecraft, generalmente los juegos q estan de moda o mas jugados,","Sudoku","Anime,MOBA,MMORPG","FPS, Acción, Deportes","Jugaba antes de los 10 a 13 años. Dejé porque era un vicio.","No juego videojuegos","Ninguno","Varios en esas","Nada"   )] <- NA
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("MOBA (Dota 2, League of legends, Mobile Legends: Bang Bang, Arena of Valor etc.)")] <- "MOBA"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("MMORPG (World of Warcraft, Guild Wars ,  Lost Ark, etc.)")] <- "MMORPG"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("Juegos de Pelea (Street Fighter)","Teken","Pelea (Street Figther, Mortal Kombat)")] <- "Pelea"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("Simulacion (Goat Simulator, The sims, Stardew Valley, etc.)")] <- "Simulacion"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("Deportes ( FIFA)","Fifa","Fútbol, Carreras, Batallas")] <- "Deportes"
DFN3$Genero_favorito[DFN3$Genero_favorito %in% c("plataformeros")] <- "Plataformero"
```

```{r}
unique(DFN3$Elemento_favorito)
```
```{r}
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Animaciones / Estilo Artístico / Calidad gráfica")] <- "Graficos"
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Beneficios del juego (movimiento físico, aumento de capacidades, etc)")] <- "Beneficios"
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Lore y Temática")] <- "Tematica"
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Versatilidad (Que lo puedas jugar en consola, móvil o pc)")] <- "Versatilidad"
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Historias o personajes conocidos o populares")] <- "Propiedad_intelectual_popular"
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Freneticidad (Rapidez del gameplay y el constante fretetismo)", "Gameplay", "Sistema de juego, dinamismo","Mecánicas de juego", "Jugabilidad / Mecánicas" )] <- "Jugabilidad"
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Su desarrolladora (Ubisoft, Tencent, Activision, etc)")] <- "Desarrolladora"
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Su popularidad")] <- "Popularidad"
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Requerimientos del sistema aceptables")] <- "Requerimientos"
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("0","nimaciones, lore y jugabilidad")] <- NA
DFN3$Elemento_favorito[DFN3$Elemento_favorito %in% c("Historia (Resident evil, Call of duty)")] <- "Historia"
```

```{r}
unique(DFN3$Dispositivo)
```
```{r}
DFN3$Dispositivo[DFN3$Dispositivo %in% c("PC (Computadora)")] <- "PC"
DFN3$Dispositivo[DFN3$Dispositivo %in% c("Consola de videojuegos (Xbox, PlayStation, Nintendo Switch, etc)")] <- "Consola"
DFN3$Dispositivo[DFN3$Dispositivo %in% c("todas las anteriores","0")] <- NA
DFN3$Dispositivo[DFN3$Dispositivo %in% c("Dispositivos moviles (Celular, Tablet, etc.)","Pc cel" ,"Pc y ps4" )] <- "Dispositivo Movil"

```

```{r}
unique(DFN3$Metodo_de_enterarse)
```
```{r}
DFN3$Metodo_de_enterarse[DFN3$Metodo_de_enterarse %in% c("Recomendaciones de circulo personal (Amigos, familiares, etc)","Mi hermano antes me invitó a jugar","Amigos")] <- "Círculo personal"
DFN3$Metodo_de_enterarse[DFN3$Metodo_de_enterarse %in% c("Anuncio en Redes Sociales (Facebook, twitter, Instagram, Tik Tok etc.)" )] <- "Redes sociales"
DFN3$Metodo_de_enterarse[DFN3$Metodo_de_enterarse %in% c("Tienda de Aplicaciones (Steam, Epic Games Stores, Play Store, etc)" )] <- "Tienda de aplicaciones"
DFN3$Metodo_de_enterarse[DFN3$Metodo_de_enterarse %in% c("Recomendaciones de influencers (Youtubers, streamers, etc.)" )] <- "Influencers"
DFN3$Metodo_de_enterarse[DFN3$Metodo_de_enterarse %in% c("Foros o comunidades (Discord, Reddit, memes en redes sociales, etc)" )] <- "Foros o comunidades"
DFN3$Metodo_de_enterarse[DFN3$Metodo_de_enterarse %in% c("Suscripciones (Amazon Prime gaming, Xbox game pass, PlayStation Now, etc.)" )] <- "Suscripciones"
DFN3$Metodo_de_enterarse[DFN3$Metodo_de_enterarse %in% c("Publicidad en television" )] <- "Television"
DFN3$Metodo_de_enterarse[DFN3$Metodo_de_enterarse %in% c("spam de bruss"   )] <- NA
```

```{r}
unique(DFN3$Departamento)
```
```{r}
DFN3$Departamento[DFN3$Departamento %in% c("Ancash" )] <- "Áncash"
```

```{r}
unique(DFN3$Dinero_gastado)
```
```{r}
DFN3$Dinero_gastado[DFN3$Dinero_gastado %in% c("080" )] <- "80"

```

```{r}
DFN3$Genero[DFN3$Genero %in% c("Comunidad LBGTIQ+" )] <- "No binario"
unique (DFN3$Genero)
```


```{r}
NumCol<-c("Edad","Años_Jugando","Horas_libres_semanales","Horas_de_juego_semanales","Personas_con_quien_juega","Dinero_gastado","Semanas_pase_de_batalla","Meses_actualizacion")
```
```{r}
FactCol<-names(DFN3)[!names(DFN3) %in% NumCol]
```

```{r}
DFN3[FactCol] <-lapply(DFN3[FactCol], FUN = factor)
DFN3$Dinero_gastado <- as.numeric(as.character(DFN3$Dinero_gastado))

```

```{r}
summary(DFN3)
```
```{r}
DFN3$Meses_actualizacion[DFN3$Meses_actualizacion > 10] <- NA
plot(DFN3$Meses_actualizacion)
```

```{r}
DFN3$Horas_de_juego_semanales[DFN3$Horas_libres_semanales<DFN3$Horas_de_juego_semanales]<-NA

summary(DFN3)
```
```{r}
DFN3$Semanas_pase_de_batalla[DFN3$Semanas_pase_de_batalla>53]<-NA  #Un año tiene 53 semanas y consideramos ilógico que alguien que quiera estar más de 1 año en la misma temporada de un juego

DFN3$Horas_libres_semanales[DFN3$Horas_libres_semanales>60]<-NA 
boxplot(DFN3$Horas_libres_semanales)
```

```{r}
summary(DFN3)
```
```{r}
summary(DFN3)
```
```{r}
filter(DFN3,DFN3$Apellidos=="Meneses Yangali")
```

```{r}
write_csv(DFN3,"Limpieza_final.csv")
```
