---
title: "Análisis de la relación entre el colegio de procedencia y la prepación preuniversitaria en el rendimiento académico de los estudiantes de UTEC"
date: "`r Sys.Date()`"
output:
  ioslides_presentation: default
  beamer_presentation: default
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## **Relevancia del estudio**
La relación entre el colegio de procedencia y la preparación pre universitaria con el rendimiento académico es de suma importancia, ya que este puede generar un impacto positivo o negativo en el desenvolvimiento de los estudiantes durante su etapa universitaria. Desde el lado estadístico se pueden recoger diversas variables con respecto a la zona geográfica del centro de estudios, el año de egreso, promedio obtenido, tipo de colegio, entre otros.

### **Objetivo general: **
Analizar la relación entre el colegio de procedencia y la preparación preuniversitaria con el rendimiento académico de los estudiantes de la Universidad de Ingeniería y Tecnología (UTEC)

### **Objetivos específicos: **
- Explorar la influencia del tipo de colegio de procedencia (público, privado, nacional, internacional) en el rendimiento académico de los estudiantes universitarios de UTEC.
- Evaluar el impacto de la preparación preuniversitaria en el rendimiento académico de los estudiantes universitarios, considerando aspectos como la experiencia en programas de tutoría, cursos de nivelación, preparación para exámenes de ingreso, etc.
- Explorar las percepciones de los estudiantes universitarios sobre la calidad de la educación recibida en su colegio de procedencia y su relación con su rendimiento académico en UTEC.
- Comparar el rendimiento académico de los estudiantes universitarios provenientes de diferentes regiones geográficas (local, regional, nacional o internacional).

## **Variables**
### **Variables numéricas**
- Tiempo de estudio
- Promedio de egreso
- Tiempo de preparación para la universidad
- Puntaje obtenido en el examen de ingreso

### **Variables categóricas**
- Tipo de colegio
- Región
- Año de egreso
- Nivelación preuniversitaria
- Rendimiento académico

### **Herramientas de recolección**
Realizamos la siguiente encuesta mediante Google Forms: 
<https://docs.google.com/forms/d/1TcdGEu102XkWxzdulNk7n4TVa7I9ZXXhIhycg7dXkAw/edit>

## **Análisis descriptivo**

## **Análisis probabilístico**

### **Eventos**
### **Variables (discretas y continuas)**

## **Probabilidades**

## **Conclusiones**



