<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Estado de las aulas de UTEC fuera del horario de clases</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="S4_Informe_files/libs/clipboard/clipboard.min.js"></script>
<script src="S4_Informe_files/libs/quarto-html/quarto.js"></script>
<script src="S4_Informe_files/libs/quarto-html/popper.min.js"></script>
<script src="S4_Informe_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="S4_Informe_files/libs/quarto-html/anchor.min.js"></script>
<link href="S4_Informe_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="S4_Informe_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="S4_Informe_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="S4_Informe_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="S4_Informe_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción</a>
  <ul class="collapse">
  <li><a href="#relevancia" id="toc-relevancia" class="nav-link" data-scroll-target="#relevancia">Relevancia</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos">Objetivos</a></li>
  <li><a href="#contexto" id="toc-contexto" class="nav-link" data-scroll-target="#contexto">Contexto</a></li>
  <li><a href="#proceso-de-recolección" id="toc-proceso-de-recolección" class="nav-link" data-scroll-target="#proceso-de-recolección">Proceso de recolección</a></li>
  <li><a href="#librerías" id="toc-librerías" class="nav-link" data-scroll-target="#librerías">Librerías</a></li>
  <li><a href="#funciones" id="toc-funciones" class="nav-link" data-scroll-target="#funciones">Funciones</a>
  <ul class="collapse">
  <li><a href="#redondeo" id="toc-redondeo" class="nav-link" data-scroll-target="#redondeo">Redondeo</a></li>
  <li><a href="#covarianza" id="toc-covarianza" class="nav-link" data-scroll-target="#covarianza">Covarianza</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#base-de-datos" id="toc-base-de-datos" class="nav-link" data-scroll-target="#base-de-datos">Base de datos</a>
  <ul class="collapse">
  <li><a href="#carga-de-datos" id="toc-carga-de-datos" class="nav-link" data-scroll-target="#carga-de-datos">Carga de datos</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">Variables</a>
  <ul class="collapse">
  <li><a href="#renombrar-variables" id="toc-renombrar-variables" class="nav-link" data-scroll-target="#renombrar-variables">Renombrar variables</a></li>
  <li><a href="#recategorización-de-variables" id="toc-recategorización-de-variables" class="nav-link" data-scroll-target="#recategorización-de-variables">Recategorización de variables</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#análisis-descriptivo" id="toc-análisis-descriptivo" class="nav-link" data-scroll-target="#análisis-descriptivo">Análisis Descriptivo</a>
  <ul class="collapse">
  <li><a href="#univariado" id="toc-univariado" class="nav-link" data-scroll-target="#univariado">Univariado</a>
  <ul class="collapse">
  <li><a href="#hora" id="toc-hora" class="nav-link" data-scroll-target="#hora">Hora</a></li>
  <li><a href="#alumnos" id="toc-alumnos" class="nav-link" data-scroll-target="#alumnos">Alumnos</a></li>
  </ul></li>
  <li><a href="#bivariado" id="toc-bivariado" class="nav-link" data-scroll-target="#bivariado">Bivariado</a>
  <ul class="collapse">
  <li><a href="#tipos-de-aula-aforo" id="toc-tipos-de-aula-aforo" class="nav-link" data-scroll-target="#tipos-de-aula-aforo">Tipos de aula ~ Aforo</a></li>
  <li><a href="#limpieza-tiempo-ultima-clase---toma-de-muestra-minutos-tipo-de-aulas" id="toc-limpieza-tiempo-ultima-clase---toma-de-muestra-minutos-tipo-de-aulas" class="nav-link" data-scroll-target="#limpieza-tiempo-ultima-clase---toma-de-muestra-minutos-tipo-de-aulas">Limpieza ~ Tiempo (Ultima clase - Toma de muestra (minutos) ~ Tipo de aulas</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#análisis-probabilístico" id="toc-análisis-probabilístico" class="nav-link" data-scroll-target="#análisis-probabilístico">Análisis probabilístico</a>
  <ul class="collapse">
  <li><a href="#probabilidad-empírica" id="toc-probabilidad-empírica" class="nav-link" data-scroll-target="#probabilidad-empírica">Probabilidad empírica</a>
  <ul class="collapse">
  <li><a href="#variable-tipo-de-aula-mixta-normal-pequeña-o-laboratorio" id="toc-variable-tipo-de-aula-mixta-normal-pequeña-o-laboratorio" class="nav-link" data-scroll-target="#variable-tipo-de-aula-mixta-normal-pequeña-o-laboratorio">Variable tipo de aula (mixta, normal, pequeña o laboratorio)</a></li>
  <li><a href="#variable-limpioescala-de-limpieza-de-un-aula" id="toc-variable-limpioescala-de-limpieza-de-un-aula" class="nav-link" data-scroll-target="#variable-limpioescala-de-limpieza-de-un-aula">Variable Limpio(escala de limpieza de un aula)</a></li>
  <li><a href="#variable-orden" id="toc-variable-orden" class="nav-link" data-scroll-target="#variable-orden">Variable orden</a></li>
  <li><a href="#variable-aforo" id="toc-variable-aforo" class="nav-link" data-scroll-target="#variable-aforo">Variable Aforo</a></li>
  </ul></li>
  <li><a href="#probabilidad-condicional" id="toc-probabilidad-condicional" class="nav-link" data-scroll-target="#probabilidad-condicional">Probabilidad condicional</a>
  <ul class="collapse">
  <li><a href="#eventos-dependientes" id="toc-eventos-dependientes" class="nav-link" data-scroll-target="#eventos-dependientes">Eventos dependientes</a></li>
  <li><a href="#eventos-independientes" id="toc-eventos-independientes" class="nav-link" data-scroll-target="#eventos-independientes">Eventos independientes</a></li>
  </ul></li>
  <li><a href="#variables-discretas" id="toc-variables-discretas" class="nav-link" data-scroll-target="#variables-discretas">Variables discretas</a>
  <ul class="collapse">
  <li><a href="#número-de-salones-recién-limpios-en-una-muestra-de-tamaño-a" id="toc-número-de-salones-recién-limpios-en-una-muestra-de-tamaño-a" class="nav-link" data-scroll-target="#número-de-salones-recién-limpios-en-una-muestra-de-tamaño-a">Número de salones recién limpios en una muestra de tamaño a</a></li>
  <li><a href="#número-de-intentos-hasta-encontrar-salón-vacío" id="toc-número-de-intentos-hasta-encontrar-salón-vacío" class="nav-link" data-scroll-target="#número-de-intentos-hasta-encontrar-salón-vacío">Número de intentos hasta encontrar salón vacío</a></li>
  </ul></li>
  <li><a href="#variables-continuas" id="toc-variables-continuas" class="nav-link" data-scroll-target="#variables-continuas">Variables Continuas</a>
  <ul class="collapse">
  <li><a href="#ultima-clase-en-horas" id="toc-ultima-clase-en-horas" class="nav-link" data-scroll-target="#ultima-clase-en-horas">Ultima clase en horas</a></li>
  <li><a href="#siguiente-clase-en-horas" id="toc-siguiente-clase-en-horas" class="nav-link" data-scroll-target="#siguiente-clase-en-horas">Siguiente clase en horas</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">Conclusiones</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Estado de las aulas de UTEC fuera del horario de clases</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introducción" class="level1">
<h1>Introducción</h1>
<section id="relevancia" class="level2">
<h2 class="anchored" data-anchor-id="relevancia">Relevancia</h2>
<p>Los ambientes con los que cuenta UTEC para que sus alumnos estudien ya sea de manera grupal o individual no siempre satisface el número de estudiantes que se encuentran fuera de clases. Es por ello que algunos optan por aulas desocupadas. Estas a pesar de no estar en uso deben de cumplir con un buen estado para que los alumnos tengan un ambiente agradable.</p>
</section>
<section id="objetivos" class="level2">
<h2 class="anchored" data-anchor-id="objetivos">Objetivos</h2>
<ul>
<li><p>Verificar que la limpieza de las aulas de la Universidad de Ingeniería y Tecnología, cumplan con el aforo permitido y presenten un buen proceso de saneamiento.</p></li>
<li><p>Comprender la relación que existe entre los alumnos de UTEC y el estado de las aulas fuera de clases</p></li>
<li><p>Brindar información a la comunidad universitaria y servicio de limpieza de la Universidad de Ingeniería y Tecnología, con el fin de mejorar la planificación y mantenimiento de limpieza de las aulas de UTEC.</p></li>
</ul>
</section>
<section id="contexto" class="level2">
<h2 class="anchored" data-anchor-id="contexto">Contexto</h2>
<p>Las universidades deben garantizar un entorno limpio y ordenado en sus aulas para brindar a sus estudiantes un ambiente adecuado durante sus clases. La Universidad de Ingeniería y Tecnología (UTEC), ubicada en el distrito de Barranco, cuenta con una población estudiantil de aproximadamente 4000 estudiantes tanto de pre-grado como de postgrado. Actualmente, la universidad tiene un horario de limpieza establecido para cada aula. Sin embargo, sería beneficioso reorganizar el horario de limpieza considerando las aulas más frecuentadas por los estudiantes, de manera que estén en óptimas condiciones fuera del horario de clases, ya que algunos estudiantes utilizan estos espacios para estudiar durante sus horas libres o llevar a cabo otras actividades. El presente estudio se centra en analizar la relación entre los alumnos de UTEC y el estado de las aulas fuera de clases, así como la influencia de los estudiantes que utilizan las aulas para estudiar en el estado general de las mismas. La información obtenida será utilizada para informar y mejorar el proceso de limpieza y mantenimiento de las aulas en la Universidad de Ingeniería y Tecnología</p>
</section>
<section id="proceso-de-recolección" class="level2">
<h2 class="anchored" data-anchor-id="proceso-de-recolección">Proceso de recolección</h2>
<p>Accedimos a las aulas que no estaban reservadas para actividades especificas, como reuniones, asesorías, clases entre otras. A distintas horas y distintas fechas. Mediante la observación anotamos los datos que requeríamos. Además también usamos la información que nos brindan las cartillas y los horarios que se encuentran en cada aula.</p>
</section>
<section id="librerías" class="level2">
<h2 class="anchored" data-anchor-id="librerías">Librerías</h2>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="funciones" class="level2">
<h2 class="anchored" data-anchor-id="funciones">Funciones</h2>
<section id="redondeo" class="level3">
<h3 class="anchored" data-anchor-id="redondeo">Redondeo</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">round</span>(x, <span class="at">digits =</span> <span class="dv">2</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="covarianza" class="level3">
<h3 class="anchored" data-anchor-id="covarianza">Covarianza</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">&lt;-</span> <span class="cf">function</span>(x, ...){</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">sd</span>(x, ...)<span class="sc">/</span><span class="fu">mean</span>(x, ...))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="base-de-datos" class="level1">
<h1>Base de datos</h1>
<section id="carga-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="carga-de-datos">Carga de datos</h2>
<p>Usamos la librería <code>readr</code> en la cual tenemos acceso a la función <code>read_csv()</code> la cual usaremos para cargar nuestros datos a la variable <code>Data</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"BDPRO.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 150 Columns: 19
-- Column specification --------------------------------------------------------
Delimiter: ","
chr (11): Aula, Tipo, Fecha, Ordenado, Aforo, Pizarra, Tacho, UltimaLimpieza...
dbl  (8): Piso, Hora, Limpio, Dispositivos, Alumnos, Ventanas, UltimaClase, ...

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>DF</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 150 x 19
   Aula  Tipo        Piso  Hora Fecha Limpio Ordenado Aforo Dispositivos Pizarra
   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;  
 1 A903  Aula norm~     9    12 02/0~      5 Si       Si               4 Si     
 2 A906  Aula norm~     9    10 26/0~      5 No       Si               0 Si     
 3 M601  Laborator~     6    15 25/0~      5 Si       Si              10 Si     
 4 A905  Aula norm~     9    12 02/0~      3 Si       Si               2 Si     
 5 A202  Aula norm~     2    17 03/0~      4 Si       Si               3 Si     
 6 A704  Aula norm~     7    20 03/0~      3 No       No               2 Si     
 7 A705  Aula norm~     7    16 03/0~      3 No       Si               4 No     
 8 A901  Aula norm~     9    12 26/0~      4 No       Si               3 No     
 9 A702  Aula norm~     7    15 27/0~      5 No       No               3 No     
10 A1002 Aula norm~    10    12 02/0~      3 Si       Si               4 Si     
# i 140 more rows
# i 9 more variables: Alumnos &lt;dbl&gt;, Ventanas &lt;dbl&gt;, Tacho &lt;chr&gt;,
#   UltimaClase &lt;dbl&gt;, UltimaLimpieza &lt;chr&gt;, SiguienteClase &lt;dbl&gt;,
#   Uclaseh &lt;chr&gt;, Sclaseh &lt;chr&gt;, Intervalo &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<p>Contamos con 9 categóricas y 5 numéricas y 2 fechas</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spec</span>(DF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>cols(
  Aula = col_character(),
  Tipo = col_character(),
  Piso = col_double(),
  Hora = col_double(),
  Fecha = col_character(),
  Limpio = col_double(),
  Ordenado = col_character(),
  Aforo = col_character(),
  Dispositivos = col_double(),
  Pizarra = col_character(),
  Alumnos = col_double(),
  Ventanas = col_double(),
  Tacho = col_character(),
  UltimaClase = col_double(),
  UltimaLimpieza = col_character(),
  SiguienteClase = col_double(),
  Uclaseh = col_character(),
  Sclaseh = col_character(),
  Intervalo = col_character()
)</code></pre>
</div>
</div>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Tipo</th>
<th>Restricción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aula</td>
<td>Categórica nominal</td>
<td>Codificación que asigna UTEC a sus aulas</td>
</tr>
<tr class="even">
<td>Tipo</td>
<td>Categórica nominal</td>
<td>Aula normal, Aula pequeña, Laboratorio o Aula mixta</td>
</tr>
<tr class="odd">
<td>Piso</td>
<td>Numérica discreta</td>
<td>[1,10]</td>
</tr>
<tr class="even">
<td>Hora</td>
<td>Numérica discreta</td>
<td>[7,22]</td>
</tr>
<tr class="odd">
<td>Fecha</td>
<td>Fecha</td>
<td>A partir de 24/04</td>
</tr>
<tr class="even">
<td>Limpio</td>
<td>Categórica ordinal</td>
<td>Del 1 al 5</td>
</tr>
<tr class="odd">
<td>Ordenado</td>
<td>Categórica nominal</td>
<td>Si o no</td>
</tr>
<tr class="even">
<td>Aforo</td>
<td>Categórica nominal</td>
<td>Si o no</td>
</tr>
<tr class="odd">
<td>Dispositivos</td>
<td>Numérica discreta</td>
<td>[0,5]</td>
</tr>
<tr class="even">
<td>Pizarra</td>
<td>Categórica nominal</td>
<td>Si o no</td>
</tr>
<tr class="odd">
<td>Alumnos</td>
<td>Numérica discreta</td>
<td>Entero mayor o igual a 0</td>
</tr>
<tr class="even">
<td>Ventanas</td>
<td>Numérica discreta</td>
<td>Entero mayor o igual a 0</td>
</tr>
<tr class="odd">
<td>Tacho</td>
<td>Categórica nominal</td>
<td>Si o no</td>
</tr>
<tr class="even">
<td>Ultima clase</td>
<td>Numérica continua</td>
<td>Número positivo</td>
</tr>
<tr class="odd">
<td>Ultima limpieza</td>
<td>Fecha</td>
<td>A partir de 17/04</td>
</tr>
<tr class="even">
<td>Siguiente clase</td>
<td>Numérica continua</td>
<td>Número positivo</td>
</tr>
</tbody>
</table>
<section id="renombrar-variables" class="level3">
<h3 class="anchored" data-anchor-id="renombrar-variables">Renombrar variables</h3>
<p>Ahora que todas las variables están correctamente definidas. Renombraremos unas cuentas para facilitar su uso al momento de programar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Uclase =</span> UltimaClase) <span class="ot">-&gt;</span> DF</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">ULimpieza =</span> UltimaLimpieza) <span class="ot">-&gt;</span> DF</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Sclase =</span> SiguienteClase) <span class="ot">-&gt;</span> DF</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Disp =</span> Dispositivos) <span class="ot">-&gt;</span> DF</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Ord =</span> Ordenado) <span class="ot">-&gt;</span> DF</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>DF</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 150 x 19
   Aula  Tipo         Piso  Hora Fecha  Limpio Ord   Aforo  Disp Pizarra Alumnos
   &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
 1 A903  Aula normal     9    12 02/05~      5 Si    Si        4 Si            9
 2 A906  Aula normal     9    10 26/04~      5 No    Si        0 Si            6
 3 M601  Laboratorio     6    15 25/04~      5 Si    Si       10 Si            0
 4 A905  Aula normal     9    12 02/05~      3 Si    Si        2 Si            2
 5 A202  Aula normal     2    17 03/05~      4 Si    Si        3 Si            8
 6 A704  Aula normal     7    20 03/05~      3 No    No        2 Si            0
 7 A705  Aula normal     7    16 03/05~      3 No    Si        4 No            1
 8 A901  Aula normal     9    12 26/04~      4 No    Si        3 No            7
 9 A702  Aula normal     7    15 27/04~      5 No    No        3 No            0
10 A1002 Aula normal    10    12 02/05~      3 Si    Si        4 Si           10
# i 140 more rows
# i 8 more variables: Ventanas &lt;dbl&gt;, Tacho &lt;chr&gt;, Uclase &lt;dbl&gt;,
#   ULimpieza &lt;chr&gt;, Sclase &lt;dbl&gt;, Uclaseh &lt;chr&gt;, Sclaseh &lt;chr&gt;,
#   Intervalo &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="recategorización-de-variables" class="level3">
<h3 class="anchored" data-anchor-id="recategorización-de-variables">Recategorización de variables</h3>
<p>Debido a que la variable <code>Limpio</code> es una escala de satisfacción del 1 al 5 <code>R</code> lo toma como numérica, por lo que la recategorizaremos a <code>categórica.</code></p>
<p>Además a las variables <code>Fecha</code> y <code>ULipieza</code> las definiremos de tipo <code>fecha</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>Limpio <span class="ot">&lt;-</span> <span class="fu">as.character</span>(DF<span class="sc">$</span>Limpio)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>Uclaseh <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, DF<span class="sc">$</span>Uclaseh)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>Uclaseh <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(DF<span class="sc">$</span>Uclaseh)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>Sclaseh <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">","</span>, <span class="st">"."</span>, DF<span class="sc">$</span>Sclaseh)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>Sclaseh <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(DF<span class="sc">$</span>Sclaseh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="análisis-descriptivo" class="level1">
<h1>Análisis Descriptivo</h1>
<section id="univariado" class="level2">
<h2 class="anchored" data-anchor-id="univariado">Univariado</h2>
<section id="hora" class="level3">
<h3 class="anchored" data-anchor-id="hora">Hora</h3>
<section id="descriptores-numéricos" class="level4">
<h4 class="anchored" data-anchor-id="descriptores-numéricos">Descriptores numéricos</h4>
<p>En esta variable a diferencia de la anterior observamos que la diferencia entre el promedio y la mediana es mínima. Esto se podría interpretar como una mejor distribución de los datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r</span>(<span class="fu">mean</span>(DF<span class="sc">$</span>Hora))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.69</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(DF<span class="sc">$</span>Hora)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15</code></pre>
</div>
</div>
<p>En este caso el coeficiente de variación es menor que 0.3 por lo que el promedio sera quien determine la distribución de los datos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r</span>(<span class="fu">cv</span>(DF<span class="sc">$</span>Hora))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2</code></pre>
</div>
</div>
</section>
<section id="gráficos" class="level4">
<h4 class="anchored" data-anchor-id="gráficos">Gráficos</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
   9   13   15   17   21 </code></pre>
</div>
</div>
<p>Según el diagrama de caja podemos observar que la mayor parte de nuestros datos se encuentran entre las 13 y 17 horas. Además de no tener datos atípicos y mostrar una buena distribución de los datos en la variable.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ahora si ubicamos la información en un gráfico de barras, contemplamos la existencia de 2 modas como habíamos mencionado anteriormente. Las cuales vendrían a ser las 13 y 15 horas. Interpretando estos datos junto con la gráfica, concluimos que es mas probable encontrar un salón desocupado a las 13 y entre las 15 y 17 horas.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="alumnos" class="level3">
<h3 class="anchored" data-anchor-id="alumnos">Alumnos</h3>
<section id="descriptores-numéricos-1" class="level4">
<h4 class="anchored" data-anchor-id="descriptores-numéricos-1">Descriptores numéricos</h4>
<p>Es notable que el coeficiente de variación es alto, esto nos da a entender que tiene una distribución muy dispersa, lo que podría significar un sesgo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r</span>(<span class="fu">cv</span>(DF<span class="sc">$</span>Alumnos))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.92</code></pre>
</div>
</div>
<p>Para corroborar esto nos fijaremos en el promedio y la mediana. Debido a que el promedio &gt; mediana , esperaremos ver un sesgo a la derecha en el histograma</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r</span>(<span class="fu">mean</span>(DF<span class="sc">$</span>Alumnos))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(DF<span class="sc">$</span>Alumnos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
</section>
<section id="gráficos-1" class="level4">
<h4 class="anchored" data-anchor-id="gráficos-1">Gráficos</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Consideramos que un diagrama de caja es lo ideal para mostrar esta variable, debido a que podemos ubicar de mejor manera los datos. Concluyendo que a pesar que los datos se encuentran al rededor de 5 alumnos. Un 25% de las veces que se tomaron los datos las aulas se encontraban vacías. Por lo que Podemos encontrar de 1 hasta 9 alumnos en un salón. Sin embargo también es muy probable de que el aula este vacía.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(DF<span class="sc">$</span>Alumnos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0%   25%   50%   75%  100% 
 0.00  1.00  5.00  9.75 24.00 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Evento atómico: Probabilidad empírica de que el aula este vacía (0 alumnos)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1866667</code></pre>
</div>
</div>
<p>Esto puede servir para un alumno que desee encontrar aula vacía</p>
</section>
</section>
</section>
<section id="bivariado" class="level2">
<h2 class="anchored" data-anchor-id="bivariado">Bivariado</h2>
<section id="tipos-de-aula-aforo" class="level3">
<h3 class="anchored" data-anchor-id="tipos-de-aula-aforo">Tipos de aula ~ Aforo</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>De acuerdo al gráfico presentado, se muestra la distribución de los diferentes tipos de aulas en UTEC en relación con su capacidad de aforo. Este análisis estadístico nos permite observar la proporción de aulas que cumplen con el aforo establecido.</p>
<p>Los resultados revelan que las aulas mixtas de UTEC son las que mejor cumplen con el aforo establecido, mostrando una proporción significativa de aulas que respetan dicha capacidad. Por otro lado, la mayoría de las aulas normales también cumplen con el aforo, aunque se observa que más de la mitad de los registros correspondientes a estas aulas indican que no se cumple el aforo permitido. Por último, se destaca que las aulas pequeñas son el tipo de aula en el cual no se cumple el aforo establecido.</p>
<p>Estos hallazgos evidencian la importancia de monitorear y garantizar el cumplimiento del aforo en las aulas, especialmente en aquellas de menor capacidad, a fin de asegurar un ambiente adecuado y seguro para los estudiantes y el personal académico.</p>
</section>
<section id="limpieza-tiempo-ultima-clase---toma-de-muestra-minutos-tipo-de-aulas" class="level3">
<h3 class="anchored" data-anchor-id="limpieza-tiempo-ultima-clase---toma-de-muestra-minutos-tipo-de-aulas">Limpieza ~ Tiempo (Ultima clase - Toma de muestra (minutos) ~ Tipo de aulas</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>De acuerdo con el gráfico presentado, podemos observar cuatro tipos de aulas (mixtas, normales, pequeñas y laboratorios), con puntuaciones de limpieza del 0 al 5 (eje y), considerando 0 como considerablemente sucias y 5 como considerablemente limpias. Estas puntuaciones están relacionadas con el tiempo transcurrido en minutos desde la última clase hasta el momento en que se tomó la muestra (eje x).</p>
<p>En cuanto a las aulas mixtas, en su mayoría obtienen puntuaciones de 4 y 5. Las muestras no superan los 360 minutos, lo que indica que durante los primeros 360 minutos desde el final de una clase, estas aulas logran mantenerse limpias y como mínimo se encuentran con una calificación de 2, lo cual significa que están sucias pero no en gran medida.</p>
<p>Con respecto a las aulas normales, se destacan puntuaciones de 0 y 5, que representan extremadamente sucias y extremadamente limpias. Podemos observar en el gráfico que este tipo de aulas son las que más logran mantenerse limpias a medida que pasa el tiempo, llegando a 1500 minutos desde la última clase. Sin embargo, es importante considerar que, de acuerdo con el gráfico, en las aulas normales se pueden encontrar todas las escalas de limpieza, desde 0 hasta 5, pero a medida que pasa más tiempo desde la última clase, es más probable encontrar un aula muy limpia o, en ciertas ocasiones, extremadamente sucia.</p>
<p>En cuanto a las aulas pequeñas, se observa un patrón similar al de las aulas normales. Sin embargo, en este caso, a medida que pasa más tiempo, es más probable encontrar un aula con una limpieza de escala 2, lo cual significa que está sucia en un grado muy bajo.</p>
<p>Por último, en el caso de los laboratorios, a medida que pasa más tiempo, alrededor de 620 minutos después de la última clase, la mayoría de los laboratorios se mantienen limpios en gran medida, con pequeños detalles que evitan una calificación más alta pero sin problemas significativos de suciedad en el aula. Esto indica que, al igual que las aulas normales, los laboratorios logran mantenerse limpios a medida que pasa el tiempo.</p>
<p>En conclusión, el análisis estadístico del gráfico muestra que las aulas mixtas, normales, pequeñas y los laboratorios tienen diferentes patrones de limpieza a lo largo del tiempo. Las aulas mixtas tienden a mantenerse limpias durante los primeros 360 minutos, las aulas normales logran mantenerse limpias en mayor medida a medida que pasa más tiempo, las aulas pequeñas presentan una limpieza de escala baja y los laboratorios tienden a mantenerse limpios en gran medida con el paso del tiempo.</p>
</section>
</section>
</section>
<section id="análisis-probabilístico" class="level1">
<h1>Análisis probabilístico</h1>
<section id="probabilidad-empírica" class="level2">
<h2 class="anchored" data-anchor-id="probabilidad-empírica">Probabilidad empírica</h2>
<section id="variable-tipo-de-aula-mixta-normal-pequeña-o-laboratorio" class="level3">
<h3 class="anchored" data-anchor-id="variable-tipo-de-aula-mixta-normal-pequeña-o-laboratorio">Variable tipo de aula (mixta, normal, pequeña o laboratorio)</h3>
<div class="cell">

</div>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><em>Tipo de Aula</em></th>
<th style="text-align: center;"><em>Repeticiones</em></th>
<th style="text-align: center;"><em>Probabilidad</em></th>
<th style="text-align: center;"><em>Evento atómico</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><em>Aula Mixta</em></td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">Probabilidad de encontrar un aula mixta que no tenga ningún evento programado en una muestra de tamaño 150</td>
</tr>
<tr class="even">
<td style="text-align: center;"><em>Aula Normal</em></td>
<td style="text-align: center;">99</td>
<td style="text-align: center;">0.66</td>
<td style="text-align: center;">Probabilidad de encontrar un aula normal que no tenga ningún evento programado en una muestra de tamaño 150</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><em>Aula Pequeña</em></td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">Probabilidad de encontrar un aula pequeña que no tenga ningún evento programado en una muestra de tamaño 150</td>
</tr>
<tr class="even">
<td style="text-align: center;"><em>Laboratorio</em></td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.04</td>
<td style="text-align: center;">Probabilidad de encontrar un laboratorio que no tenga ningún evento programado en una muestra de tamaño 150</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</section>
<section id="variable-limpioescala-de-limpieza-de-un-aula" class="level3">
<h3 class="anchored" data-anchor-id="variable-limpioescala-de-limpieza-de-un-aula">Variable Limpio(escala de limpieza de un aula)</h3>
<div class="cell">

</div>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><em>Nivel</em></th>
<th style="text-align: center;"><em>Repeticiones</em></th>
<th style="text-align: center;"><em>Probabilidad</em></th>
<th style="text-align: center;"><em>Unidad</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">Probabilidad de encontrar un aula con un nivel de suciedad 0 en una muestra de tamaño 150</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">0.07</td>
<td style="text-align: center;">Probabilidad de encontrar un aula con un nivel de suciedad 1 en una muestra de tamaño 150</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">Probabilidad de encontrar un aula con un nivel de suciedad 2 en una muestra de tamaño 150</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">0.19</td>
<td style="text-align: center;">Probabilidad de encontrar un aula con un nivel de suciedad 3 en una muestra de tamaño 150</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">0.29</td>
<td style="text-align: center;">Probabilidad de encontrar un aula con un nivel de suciedad 4 en una muestra de tamaño 150</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">47</td>
<td style="text-align: center;">0.31</td>
<td style="text-align: center;">Probabilidad de encontrar un aula con un nivel de suciedad 5 en una muestra de tamaño 150</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</section>
<section id="variable-orden" class="level3">
<h3 class="anchored" data-anchor-id="variable-orden">Variable orden</h3>
<div class="cell">

</div>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><em>Evento</em></th>
<th style="text-align: center;"><em>Repeticiones</em></th>
<th style="text-align: center;"><em>Probabilidad</em></th>
<th style="text-align: center;"><em>Unidad</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Aula desordenada</td>
<td style="text-align: center;">78</td>
<td style="text-align: center;">0.52</td>
<td style="text-align: center;">Probabilidad de encontrar un aula desordenada en una muestra de tamaño 150</td>
</tr>
<tr class="even">
<td style="text-align: center;">Aula ordenada</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">0.48</td>
<td style="text-align: center;">Probabilidad de encontrar un aula ordenada en una muestra de tamaño 150</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</section>
<section id="variable-aforo" class="level3">
<h3 class="anchored" data-anchor-id="variable-aforo">Variable Aforo</h3>
<div class="cell">

</div>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><em>Evento</em></th>
<th style="text-align: center;"><em>Repeticiones</em></th>
<th style="text-align: center;"><em>Probabilidad</em></th>
<th style="text-align: center;"><em>Unidad</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Cumple con el aforo</td>
<td style="text-align: center;">52</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">Probabilidad de que un aula cumpla con su aforo en una muestra de tamaño 150</td>
</tr>
<tr class="even">
<td style="text-align: center;">No cumple con el aforo</td>
<td style="text-align: center;">98</td>
<td style="text-align: center;">0.65</td>
<td style="text-align: center;">Probabilidad de que un aula no cumpla con su aforo en una muestra de tamaño 150</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="probabilidad-condicional" class="level2">
<h2 class="anchored" data-anchor-id="probabilidad-condicional">Probabilidad condicional</h2>
<section id="eventos-dependientes" class="level3">
<h3 class="anchored" data-anchor-id="eventos-dependientes">Eventos dependientes</h3>
<p><strong><em>PREGUNTA: Se requiere hacer una inspección para cerciorar que la universidad cumple con lo requerido para su funcionamiento. En esta ocasión se revisara el aforo de todas las aulas, sin embargo se cuenta con poco tiempo por lo que es necesario saber que tipo de aulas necesitan ser revisadas con prioridad, para esto consultan con nuestra toma de datos</em></strong></p>
<p>Para esta pregunta usaremos la variable TIPO DE AULA y AFORO</p>
<p>Para poder responder está pregunta debemos saber primero la probabilidad de que María encuentre una aula mixta, luego debemos hallar la probabilidad de que el aula este ordenada</p>
<p>Definimos los eventos</p>
<ul>
<li><p>A: “Probabilidad de encontrar un aula mixta que no tenga ningún evento programado en una muestra de tamaño 150”</p></li>
<li><p>B: “Probabilidad de que un aula cumpla con su aforo en una muestra de tamaño 150”</p></li>
</ul>
<p>Verificaremos si se cumple <span class="math inline">\(P(A \cap B) = P (A) \times P(B)\)</span> para poder saber si son independientes, entonces realizamos el siguiente calculo:</p>
<p><strong>Probabilidad que ocurra el evento A</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.14</code></pre>
</div>
</div>
<p><strong>Probabilidad que ocurra el evento B</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.65</code></pre>
</div>
</div>
<p><strong>Probabilidad de que ocurran ambos eventos A y B</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.13</code></pre>
</div>
</div>
<p>Teniendo estos resultados pasamos a ver las siguientes igualdades <span class="math inline">\(P (A) \times P(B)=0.09\)</span> y <span class="math inline">\(P(A \cap B) = 0.13\)</span> por lo que <span class="math inline">\(P(A \cap B) \neq P (A) \times P(B)\)</span> Es decir, que estos eventos no son independientes.</p>
<p><strong>Por lo tanto, la probabilidad de que ocurra A dado B</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2</code></pre>
</div>
</div>
<p><span class="math display">\[\mathbb{P}(Aula \text{ }Mixta | Cumple \text { } Aforo)=\frac{\mathbb{P}(Aula \text{ } Mixta \cap Cumple \text { } Aforo)}{\mathbb{P}(Cumple \text { } Aforo)}=0.2\]</span></p>
<p><strong>Probabilidad de B dado A</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.93</code></pre>
</div>
</div>
<p>Es mas probable que cumpla con el aforo (B) dado que el aula mixta no tenga eventos (A), a que el aula mixta no tenga eventos (A) dado que cumpla con el aforo (B)</p>
</section>
<section id="eventos-independientes" class="level3">
<h3 class="anchored" data-anchor-id="eventos-independientes">Eventos independientes</h3>
<p>Ahora definiremos otros dos eventos:</p>
<ul>
<li><p>C: “Probabilidad de encontrar un aula normal que no tenga ningún evento programado en una muestra de tamaño 150”</p></li>
<li><p>D: “Probabilidad de que un aula no cumpla con su aforo en una muestra de tamaño 150”</p></li>
</ul>
<p>Esta vez verificaremos lo siguiente <span class="math inline">\(P(A|B) = P(A)\)</span> por lo que necesitaremos una vez mas hacer unos cuantos cálculos</p>
<p><strong>Probabilidad de que ocurra C</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.66</code></pre>
</div>
</div>
<p><strong>Probabilidad de que ocurra D</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.35</code></pre>
</div>
</div>
<p><strong>Probabilidad de que ocurra C dado D</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.66</code></pre>
</div>
</div>
<p>Entonces, tendríamos que <span class="math inline">\(P(C|D)=0.66\)</span> y <span class="math inline">\(P(C)=0.66\)</span>. Por lo que se cumple <span class="math inline">\(P(C|D)=P(C\)</span>) esto significaría que estos eventos son independientes</p>
<p><strong>Probabilidad de que ocurra D dado C</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.35</code></pre>
</div>
</div>
<p>También, tendríamos que <span class="math inline">\(P(D|C)=0.35\)</span> y <span class="math inline">\(P(D)=0.35\)</span>.</p>
<p><strong>Probabilidad condicional</strong></p>
<p>Por lo tanto, la probabilidad de encontrar un aula normal (C) dado que no cumple con el aforo (D), es: <span class="math inline">\(P(C|D)=0.66\)</span></p>
<p><strong>Función para extraer el numero del día de la fecha</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>convertir_fecha_a_dia <span class="ot">&lt;-</span> <span class="cf">function</span>(date_column) {</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convertir a formato de fecha estandar</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  dates <span class="ot">&lt;-</span> <span class="fu">dmy</span>(date_column)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extraer número del día</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  day_of_year <span class="ot">&lt;-</span> <span class="fu">yday</span>(dates)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(day_of_year)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="variables-discretas" class="level2">
<h2 class="anchored" data-anchor-id="variables-discretas">Variables discretas</h2>
<section id="número-de-salones-recién-limpios-en-una-muestra-de-tamaño-a" class="level3">
<h3 class="anchored" data-anchor-id="número-de-salones-recién-limpios-en-una-muestra-de-tamaño-a">Número de salones recién limpios en una muestra de tamaño a</h3>
<p>En nuestro estudio registramos las fechas de las última limpieza de cada salón. Si restamos la fecha del registro con la última fecha de limpieza, obtenemos el número de días que han pasado desde la última limpieza.</p>
<p>Un dato que puede ser de utilidad para los alumnos es saber si al escoger un salón aleatorio este ha sido limpiado ese mismo día. Para eso calculamos la probabilidad de que la diferencia entre la fecha del registro y la ultima limpieza sea 0</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Número total de salones registrados:              150 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Número de salones limpiados el mismo día:         74 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de hallar un salon recien limpiado:  0.49 </code></pre>
</div>
</div>
<p>Con esta probabilidad empírica obtenida de nuestro estudio podemos definir una variable binomial que nos de la probabilidad de hallar un número x de salones recién limpios en una muestra de tamaño a</p>
<p><strong>Éxito: Aula haya sido limpiada el mismo día del registro.</strong></p>
<p>Por ejemplo si tomáramos una muestra de 10 salones, el histograma de la variable se vería así:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Con esto podríamos calcular la probabilidad de que encontremos más de 4 salones limpios en una muestra de 10:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r</span>(<span class="fu">pbinom</span>(<span class="dv">4</span>,<span class="dv">10</span>,n_limpios<span class="sc">/</span>n_total,<span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.61</code></pre>
</div>
</div>
</section>
<section id="número-de-intentos-hasta-encontrar-salón-vacío" class="level3">
<h3 class="anchored" data-anchor-id="número-de-intentos-hasta-encontrar-salón-vacío">Número de intentos hasta encontrar salón vacío</h3>
<p>Otra variable que puede ser de utilidad para los estudiantes es la probabilidad de que en n intentos encuentren un salón vacío.</p>
<p><strong>Éxito: Salón vacío</strong></p>
<p>Para definir esta variable primero debemos calcular la probabilidad empírica según nuestro estudio de que porcentaje de salones encontramos con 0 alumnos:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.19</code></pre>
</div>
</div>
<p>Con esto podemos definir una variable geométrica que nos daría la probabilidad de que en el intento n encontremos un salón vacío. El histograma de la variable se vería de esta forma:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>var <span class="ot">=</span> <span class="fu">rgeom</span>(<span class="dv">1000</span>,n_vacios <span class="sc">/</span> n_total )</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(var, <span class="at">breaks =</span> <span class="dv">15</span>, <span class="at">col=</span><span class="fu">rainbow</span>(<span class="dv">20</span>), <span class="at">main=</span><span class="st">"Probabilidad de que en el intento n se encuentre un salon vacío"</span>, <span class="at">xlab=</span><span class="st">"N intento"</span>, <span class="at">ylab=</span><span class="st">"Repeticiones"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(var))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Por lo tanto podemos calcular la probabilidad de que en los primeros dos intentos encontremos un salón vacío:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r</span>(<span class="fu">pgeom</span>(<span class="dv">2</span>, n_vacios <span class="sc">/</span> n_total))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.46</code></pre>
</div>
</div>
</section>
</section>
<section id="variables-continuas" class="level2">
<h2 class="anchored" data-anchor-id="variables-continuas">Variables Continuas</h2>
<section id="ultima-clase-en-horas" class="level3">
<h3 class="anchored" data-anchor-id="ultima-clase-en-horas">Ultima clase en horas</h3>
<p>Esta variable vendría a ser el tiempo en horas que transcurrió desde la ultima clase antes de la muestra y la toma de muestra</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>La media es: 1.91 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>La mediana es: 0.7 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>El rango es: 24.98 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>El primer cuartil es: 0.37 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>El tercer cuartil es: 1.63 </code></pre>
</div>
</div>
<p>La mediana de la variable <strong><code>Uclaseh</code></strong> es <strong>0.7</strong>, lo que significa que aproximadamente la mitad de los valores de la variable están por debajo de 0.7 y la otra mitad está por encima de este valor. El rango de la variable <strong><code>Uclaseh</code></strong> es 24.98, lo que significa que los valores de tiempo transcurrido y toma de la muestra varían en un rango de 24.98 unidades.</p>
<p>El <code>primer cuartil</code> es 0.3725 y el <code>tercer cuartil</code> es 1.6275. Esto significa que aproximadamente el 25% de los valores de <strong><code>Uclaseh</code></strong> son menores o iguales a 0.3725, mientras que el 75% de los valores son menores o iguales a 1.6275.</p>
<p><strong><em>Distribución exponencial</em></strong></p>
<p>Al identificar que la gráfica de la variable tiene forma exponencial, podemos utilizar la distribución exponencial para realizar cálculos relacionados con esta variable. En este caso, deseamos calcular la probabilidad acumulada de una distribución exponencial con una la media que es de 1.90 hasta el valor 3.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.79</code></pre>
</div>
</div>
</section>
<section id="siguiente-clase-en-horas" class="level3">
<h3 class="anchored" data-anchor-id="siguiente-clase-en-horas">Siguiente clase en horas</h3>
<p>Por otro lado, esta vendría a ser la contraparte de la variable anterior. El tiempo en horas que transcurrió desde la toma de la muestra y la siguiente clase</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="S4_Informe_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>La media es: 6.33 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>La mediana es: 2.49 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>El rango es: 26.97 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>El primer cuartil es: 0.67 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>El tercer cuarti es: 10.95</code></pre>
</div>
</div>
<p>La <code>mediana</code> de la variable Sclaseh es 2.49, lo que significa que aproximadamente la mitad de los valores de la variable están por debajo de 2.49 y la otra mitad está por encima de este valor. El <code>rango</code> de la variable Sclaseh es 26.97, lo que significa que los valores de tiempo transcurrido y toma de la muestra varían en un rango de 26.97 unidades.</p>
<p>El <code>primer cuartil</code> es 0.67 y el <code>tercer cuartil</code> es 10.9475. Esto significa que aproximadamente el 25% de los valores de Sclaseh son menores o iguales a 0.6725, mientras que el 75% de los valores son menores o iguales a 10.9475.</p>
<p><strong><em>Distribución exponencial</em></strong></p>
<p>Al identificar que la gráfica de la variable tiene forma exponencial, podemos utilizar la distribución exponencial para realizar cálculos relacionados con esta variable. En este caso, deseamos calcular la probabilidad acumulada de una distribución exponencial con una la media que es de 6.33 hasta el valor 5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">r</span>(<span class="fu">pexp</span>(<span class="dv">5</span>, <span class="dv">1</span><span class="sc">/</span>media, <span class="at">lower.tail =</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.55</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="conclusiones" class="level1">
<h1>Conclusiones</h1>
<ul>
<li><p>En el estudio, se evaluaron diferentes tipos de aulas en términos de limpieza en la Universidad UTEC. Se encontró que las aulas mixtas generalmente presentaban una buena clasificación de limpieza, con calificaciones altas en la escala. En las aulas normales, hubo una variedad de calificaciones, pero en general se mantuvo un estándar aceptable. Las aulas pequeñas tendieron a estar más limpias en comparación con otros tipos de aulas.</p></li>
<li><p>También tuvimos en cuenta el cumplimiento del aforo. El resultado mostró que las aulas mixtas fueron las que mejor lo cumplían, seguidas por las aulas normales, aunque más de la mitad de estas últimas no cumplían completamente. Por otro lado, las aulas pequeñas no cumplían con el aforo establecido. Estos resultados resaltan la importancia de mantener un nivel adecuado de limpieza en todas las aulas y de monitorear el cumplimiento del aforo para garantizar un ambiente saludable y seguro para el aprendizaje en UTEC. Así mismo propusimos un caso en el que simulamos como la Universidad debería darle prioridad a regular el aforo en cierto tipo de aula. Dando como resultado que no deberían de preocuparse de que las aulas mixtas no cumplan con el aforo ya que estas dos condiciones son no independientes entre si. Es decir que la probabilidad de que una aula cumpla el aforo y además sea de tipo mixta es de un 93% con una muestra de 150 observaciones.</p></li>
<li><p>En las aulas mixtas, el estado de limpieza no es óptimo cuando hay muchos alumnos debido a una menor atención en la limpieza, ya que no se utilizan con tanta frecuencia. En las aulas normales, el estado de limpieza puede variar debido a la disparidad en la frecuencia de limpieza. Sería necesario reorganizar los horarios de limpieza para abordar esta situación de manera equitativa. En las aulas pequeñas, al igual que en las mixtas, se observa una menor atención en la limpieza debido a su menor frecuencia de uso, lo que resulta en un estado intermedio de limpieza. Esto se debe al menor número de alumnos y la generación de menos suciedad. En cuanto a los laboratorios, la recolección de datos fue limitada en el estudio debido a su disponibilidad limitada fuera del horario de clases, pero se observó un mantenimiento adecuado de la limpieza en los datos recopilados.</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>