---
output:
  word_document: default
  html_document: default
---

```{r}
library(dplyr)
library(readr)
library(lubridate)
library(magrittr)
library(ISLR)
library(Matrix)
```

```{r}
DF<- read_csv("DatosSinLimpiarDF/Sismos.csv")
DFG<-read_csv("DatosSinLimpiarDF/Gas.csv")
DFG<-na.omit(DFG)
```
```{r}
Meses=c("Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre")
Meses
```

```{r}
# Datos de 1995 
Enero95<-sum(DF$Fecha=='Ene-95')
Febrero95<-sum(DF$Fecha=='Feb-95')
Marzo95<-sum(DF$Fecha=='Mar-95')
Abril95<-sum(DF$Fecha=='Abr-95')
Mayo95<-sum(DF$Fecha=='May-95')
Junio95<-sum(DF$Fecha=='Jun-95')
Julio95<-sum(DF$Fecha=='Jul-95')
Agosto95<-sum(DF$Fecha=='Ago-95')
Septiembre95<-sum(DF$Fecha=='Set-95')
Octubre95<-sum(DF$Fecha=='Oct-95')
Noviembre95<-sum(DF$Fecha=='Nov-95')
Diciembre95<-sum(DF$Fecha=='Dic-95')
Año95=c(Enero95,Febrero95,Marzo95,Abril95,Mayo95,Junio95,Julio95,Agosto95,Septiembre95,Octubre95,Noviembre95,Diciembre95)

# Datos de 1996
Enero96<-sum(DF$Fecha=='Ene-96')
Febrero96<-sum(DF$Fecha=='Feb-96')
Marzo96<-sum(DF$Fecha=='Mar-96')
Abril96<-sum(DF$Fecha=='Abr-96')
Mayo96<-sum(DF$Fecha=='May-96')
Junio96<-sum(DF$Fecha=='Jun-96')
Julio96<-sum(DF$Fecha=='Jul-96')
Agosto96<-sum(DF$Fecha=='Ago-96')
Septiembre96<-sum(DF$Fecha=='Set-96')
Octubre96<-sum(DF$Fecha=='Oct-96')
Noviembre96<-sum(DF$Fecha=='Nov-96')
Diciembre96<-sum(DF$Fecha=='Dic-96')
Año96=c(Enero96,Febrero96,Marzo96,Abril96,Mayo96,Junio96,Julio96,Agosto96,Septiembre96,Octubre96,Noviembre96,Diciembre96)

# Datos de 1997 
Enero97<-sum(DF$Fecha=='Ene-97')
Febrero97<-sum(DF$Fecha=='Feb-97')
Marzo97<-sum(DF$Fecha=='Mar-97')
Abril97<-sum(DF$Fecha=='Abr-97')
Mayo97<-sum(DF$Fecha=='May-97')
Junio97<-sum(DF$Fecha=='Jun-97')
Julio97<-sum(DF$Fecha=='Jul-97')
Agosto97<-sum(DF$Fecha=='Ago-97')
Septiembre97<-sum(DF$Fecha=='Set-97')
Octubre97<-sum(DF$Fecha=='Oct-97')
Noviembre97<-sum(DF$Fecha=='Nov-97')
Diciembre97<-sum(DF$Fecha=='Dic-97')
Año97=c(Enero97,Febrero97,Marzo97,Abril97,Mayo97,Junio97,Julio97,Agosto97,Septiembre97,Octubre97,Noviembre97,Diciembre97)

# Datos de 1998 
Enero98<-sum(DF$Fecha=='Ene-98')
Febrero98<-sum(DF$Fecha=='Feb-98')
Marzo98<-sum(DF$Fecha=='Mar-98')
Abril98<-sum(DF$Fecha=='Abr-98')
Mayo98<-sum(DF$Fecha=='May-98')
Junio98<-sum(DF$Fecha=='Jun-98')
Julio98<-sum(DF$Fecha=='Jul-98')
Agosto98<-sum(DF$Fecha=='Ago-98')
Septiembre98<-sum(DF$Fecha=='Set-98')
Octubre98<-sum(DF$Fecha=='Oct-98')
Noviembre98<-sum(DF$Fecha=='Nov-98')
Diciembre98<-sum(DF$Fecha=='Dic-98')
Año98=c(Enero98,Febrero98,Marzo98,Abril98,Mayo98,Junio98,Julio98,Agosto98,Septiembre98,Octubre98,Noviembre98,Diciembre98)

# Datos de 1999
Enero99<-sum(DF$Fecha=='Ene-99')									
Febrero99<-sum(DF$Fecha=='Feb-99')									
Marzo99<-sum(DF$Fecha=='Mar-99')									
Abril99<-sum(DF$Fecha=='Abr-99')									
Mayo99<-sum(DF$Fecha=='May-99')									
Junio99<-sum(DF$Fecha=='Jun-99')									
Julio99<-sum(DF$Fecha=='Jul-99')									
Agosto99<-sum(DF$Fecha=='Ago-99')									
Septiembre99<-sum(DF$Fecha=='Set-99')									
Octubre99<-sum(DF$Fecha=='Oct-99')									
Noviembre99<-sum(DF$Fecha=='Nov-99')									
Diciembre99<-sum(DF$Fecha=='Dic-99')									
Año99=c(Enero99,Febrero99,Marzo99,Abril99,Mayo99,Junio99,Julio99,Agosto99,Septiembre99,Octubre99,Noviembre99,Diciembre99)							

# Datos de 2000
Enero00<-sum(DF$Fecha=='Ene-00')
Febrero00<-sum(DF$Fecha=='Feb-00')
Marzo00<-sum(DF$Fecha=='Mar-00')
Abril00<-sum(DF$Fecha=='Abr-00')
Mayo00<-sum(DF$Fecha=='May-00')
Junio00<-sum(DF$Fecha=='Jun-00')
Julio00<-sum(DF$Fecha=='Jul-00')
Agosto00<-sum(DF$Fecha=='Ago-00')
Septiembre00<-sum(DF$Fecha=='Set-00')
Octubre00<-sum(DF$Fecha=='Oct-00')
Noviembre00<-sum(DF$Fecha=='Nov-00')
Diciembre00<-sum(DF$Fecha=='Dic-00')
Año00=c(Enero00,Febrero00,Marzo00,Abril00,Mayo00,Junio00,Julio00,Agosto00,Septiembre00,Octubre00,Noviembre00,Diciembre00)

# Datos de 2001
Enero01<-sum(DF$Fecha=='ene-01')
Febrero01<-sum(DF$Fecha=='feb-01')
Marzo01<-sum(DF$Fecha=='mar-01')
Abril01<-sum(DF$Fecha=='abr-01')
Mayo01<-sum(DF$Fecha=='may-01')
Junio01<-sum(DF$Fecha=='jun-01')
Julio01<-sum(DF$Fecha=='jul-01')
Agosto01<-sum(DF$Fecha=='ago-01')
Septiembre01<-sum(DF$Fecha=='Set-01')
Octubre01<-sum(DF$Fecha=='oct-01')
Noviembre01<-sum(DF$Fecha=='nov-01')
Diciembre01<-sum(DF$Fecha=='dic-01')
Año01=c(Enero01,Febrero01,Marzo01,Abril01,Mayo01,Junio01,Julio01,Agosto01,Septiembre01,Octubre01,Noviembre01,Diciembre01)

# Datos de 2002
Enero02<-sum(DF$Fecha=='ene-02')
Febrero02<-sum(DF$Fecha=='feb-02')
Marzo02<-sum(DF$Fecha=='mar-02')
Abril02<-sum(DF$Fecha=='abr-02')
Mayo02<-sum(DF$Fecha=='may-02')
Junio02<-sum(DF$Fecha=='jun-02')
Julio02<-sum(DF$Fecha=='jul-02')
Agosto02<-sum(DF$Fecha=='ago-02')
Septiembre02<-sum(DF$Fecha=='Set-02')
Octubre02<-sum(DF$Fecha=='oct-02')
Noviembre02<-sum(DF$Fecha=='nov-02')
Diciembre02<-sum(DF$Fecha=='dic-02')
Año02=c(Enero02,Febrero02,Marzo02,Abril02,Mayo02,Junio02,Julio02,Agosto02,Septiembre02,Octubre02,Noviembre02,Diciembre02)

# Datos de 2003
Enero03<-sum(DF$Fecha=='ene-03')
Febrero03<-sum(DF$Fecha=='feb-03')
Marzo03<-sum(DF$Fecha=='mar-03')
Abril03<-sum(DF$Fecha=='abr-03')
Mayo03<-sum(DF$Fecha=='may-03')
Junio03<-sum(DF$Fecha=='jun-03')
Julio03<-sum(DF$Fecha=='jul-03')
Agosto03<-sum(DF$Fecha=='ago-03')
Septiembre03<-sum(DF$Fecha=='Set-03')
Octubre03<-sum(DF$Fecha=='oct-03')
Noviembre03<-sum(DF$Fecha=='nov-03')
Diciembre03<-sum(DF$Fecha=='dic-03')
Año03=c(Enero03,Febrero03,Marzo03,Abril03,Mayo03,Junio03,Julio03,Agosto03,Septiembre03,Octubre03,Noviembre03,Diciembre03)

# Datos de 2004
Enero04<-sum(DF$Fecha=='ene-04')
Febrero04<-sum(DF$Fecha=='feb-04')
Marzo04<-sum(DF$Fecha=='mar-04')
Abril04<-sum(DF$Fecha=='abr-04')
Mayo04<-sum(DF$Fecha=='may-04')
Junio04<-sum(DF$Fecha=='jun-04')
Julio04<-sum(DF$Fecha=='jul-04')
Agosto04<-sum(DF$Fecha=='ago-04')
Septiembre04<-sum(DF$Fecha=='Set-04')
Octubre04<-sum(DF$Fecha=='oct-04')
Noviembre04<-sum(DF$Fecha=='nov-04')
Diciembre04<-sum(DF$Fecha=='dic-04')
Año04=c(Enero04,Febrero04,Marzo04,Abril04,Mayo04,Junio04,Julio04,Agosto04,Septiembre04,Octubre04,Noviembre04,Diciembre04)

# Datos de 2005
Enero05<-sum(DF$Fecha=='ene-05')
Febrero05<-sum(DF$Fecha=='feb-05')
Marzo05<-sum(DF$Fecha=='mar-05')
Abril05<-sum(DF$Fecha=='abr-05')
Mayo05<-sum(DF$Fecha=='may-05')
Junio05<-sum(DF$Fecha=='jun-05')
Julio05<-sum(DF$Fecha=='jul-05')
Agosto05<-sum(DF$Fecha=='ago-05')
Septiembre05<-sum(DF$Fecha=='Set-05')
Octubre05<-sum(DF$Fecha=='oct-05')
Noviembre05<-sum(DF$Fecha=='nov-05')
Diciembre05<-sum(DF$Fecha=='dic-05')
Año05=c(Enero05,Febrero05,Marzo05,Abril05,Mayo05,Junio05,Julio05,Agosto05,Septiembre05,Octubre05,Noviembre05,Diciembre05)

# Datos de 2006
Enero06<-sum(DF$Fecha=='ene-06')
Febrero06<-sum(DF$Fecha=='feb-06')
Marzo06<-sum(DF$Fecha=='mar-06')
Abril06<-sum(DF$Fecha=='abr-06')
Mayo06<-sum(DF$Fecha=='may-06')
Junio06<-sum(DF$Fecha=='jun-06')
Julio06<-sum(DF$Fecha=='jul-06')
Agosto06<-sum(DF$Fecha=='ago-06')
Septiembre06<-sum(DF$Fecha=='Set-06')
Octubre06<-sum(DF$Fecha=='oct-06')
Noviembre06<-sum(DF$Fecha=='nov-06')
Diciembre06<-sum(DF$Fecha=='dic-06')
Año06=c(Enero06,Febrero06,Marzo06,Abril06,Mayo06,Junio06,Julio06,Agosto06,Septiembre06,Octubre06,Noviembre06,Diciembre06)

# Datos de 2007
Enero07<-sum(DF$Fecha=='ene-07')
Febrero07<-sum(DF$Fecha=='feb-07')
Marzo07<-sum(DF$Fecha=='mar-07')
Abril07<-sum(DF$Fecha=='abr-07')
Mayo07<-sum(DF$Fecha=='may-07')
Junio07<-sum(DF$Fecha=='jun-07')
Julio07<-sum(DF$Fecha=='jul-07')
Agosto07<-sum(DF$Fecha=='ago-07')
Septiembre07<-sum(DF$Fecha=='Set-07')
Octubre07<-sum(DF$Fecha=='oct-07')
Noviembre07<-sum(DF$Fecha=='nov-07')
Diciembre07<-sum(DF$Fecha=='dic-07')
Año07=c(Enero07,Febrero07,Marzo07,Abril07,Mayo07,Junio07,Julio07,Agosto07,Septiembre07,Octubre07,Noviembre07,Diciembre07)

# Datos de 2008
Enero08<-sum(DF$Fecha=='ene-08')
Febrero08<-sum(DF$Fecha=='feb-08')
Marzo08<-sum(DF$Fecha=='mar-08')
Abril08<-sum(DF$Fecha=='abr-08')
Mayo08<-sum(DF$Fecha=='may-08')
Junio08<-sum(DF$Fecha=='jun-08')
Julio08<-sum(DF$Fecha=='jul-08')
Agosto08<-sum(DF$Fecha=='ago-08')
Septiembre08<-sum(DF$Fecha=='Set-08')
Octubre08<-sum(DF$Fecha=='oct-08')
Noviembre08<-sum(DF$Fecha=='nov-08')
Diciembre08<-sum(DF$Fecha=='dic-08')
Año08=c(Enero08,Febrero08,Marzo08,Abril08,Mayo08,Junio08,Julio08,Agosto08,Septiembre08,Octubre08,Noviembre08,Diciembre08)

# Datos de 2009
Enero09<-sum(DF$Fecha=='ene-09')
Febrero09<-sum(DF$Fecha=='feb-09')
Marzo09<-sum(DF$Fecha=='mar-09')
Abril09<-sum(DF$Fecha=='abr-09')
Mayo09<-sum(DF$Fecha=='may-09')
Junio09<-sum(DF$Fecha=='jun-09')
Julio09<-sum(DF$Fecha=='jul-09')
Agosto09<-sum(DF$Fecha=='ago-09')
Septiembre09<-sum(DF$Fecha=='Set-09')
Octubre09<-sum(DF$Fecha=='oct-09')
Noviembre09<-sum(DF$Fecha=='nov-09')
Diciembre09<-sum(DF$Fecha=='dic-09')
Año09=c(Enero09,Febrero09,Marzo09,Abril09,Mayo09,Junio09,Julio09,Agosto09,Septiembre09,Octubre09,Noviembre09,Diciembre09)

# Datos de 2010
Enero10<-sum(DF$Fecha=='ene-10')
Febrero10<-sum(DF$Fecha=='feb-10')
Marzo10<-sum(DF$Fecha=='mar-10')
Abril10<-sum(DF$Fecha=='abr-10')
Mayo10<-sum(DF$Fecha=='may-10')
Junio10<-sum(DF$Fecha=='jun-10')
Julio10<-sum(DF$Fecha=='jul-10')
Agosto10<-sum(DF$Fecha=='ago-10')
Septiembre10<-sum(DF$Fecha=='Set-10')
Octubre10<-sum(DF$Fecha=='oct-10')
Noviembre10<-sum(DF$Fecha=='nov-10')
Diciembre10<-sum(DF$Fecha=='dic-10')
Año10=c(Enero10,Febrero10,Marzo10,Abril10,Mayo10,Junio10,Julio10,Agosto10,Septiembre10,Octubre10,Noviembre10,Diciembre10)
```

```{r}
Años=data.frame(Meses,Año95,Año96,Año97,Año98,Año99,Año00,Año01,Año02,Año03,Año04,Año05,Año06,Año07,Año09,Año10)
```
```{r}
Fechas=c("Ene-95","Feb-95","Mar-95","Abr-95","May-95","Jun-95","Jul-95","Agos-95","Sep-95","Oct-95","Nov-95","Dic-95","Ene-96","Feb-96","Mar-96","Abr-96","May-96","Jun-96","Jul-96","Ago-96","Sep-96","Oct-96","Nov-96","Dic-96","Ene-97","Feb-97","Mar-97","Abr-97","May-97","Jun-97","Jul-97","Ago-97","Sep-97","Oct-97","Nov-97","Dic-97","Ene-98","Feb-98","Mar-98","Abr-98","May-98","Jun-98","Jul-98","Ago-98","Sep-98","Oct-98","Nov-98","Dic-98","Ene-99","Feb-99","Marz-99","Abr-99","May-99","Jun-99","Jul-99","Ago-99","Sep-99","Oct-99","Nov-99","Dic-99","Ene-00","Feb-00","Mar-00","Abr-00","May-00","Jun-00","Jul-00","Ago-00","Sep-00","Oct-00","Nov-00","Dic-01","Ene-01","Feb-01","Mar-01","Abr-01","May-01","Jun-01","Jul-01","Ago-01","Sep-01","Oct-01","Nov-01","Dic-01","Ene-02","Feb-02","Mar-02","Abr-02","May-02","Jun-02","Jul-02","Ago-02","Sep-02","Oct-02","Nov-02","Dic-02","Ene-03","Feb-03","Mar-03","Abr-03","May-03","Jun-03","Jul-03","Ago-03","Sep-03","Oct-03","Nov-03","Dic-03","Ene-04","Feb-04","Mar-04","Abr-04","May-04","Jun-04","Jul-04","Ago-04","Sep-04","Oct-04","Nov-04","Dic-04","Ene-05","Feb-05","Mar-05","Abr-05","May-05","Jun-05","Jul-05","Ago-05","Sep-05","Oct-05","Nov-05","Dic-05","Ene-06","Feb-06","Mar-06","Abr-06","May-06","Jun-06","Jul-06","Ago-06","Sep-06","Oct-06","Nov-06","Dic-06","Ene-07","Feb-07","Mar-70","Abr-70","May-07","Jun-07","Jul-07","Ago-07","Sep-07","Oct-07","Nov-07","Dic-07","Ene-08","Feb-08","Mar-08","Abr-08","May-08","Jun-08","Jul-08","Ago-08","Sep-08","Oct-08","Nov-08","Dic-08","Ene-09","Feb-09","Mar-09","Abr-09","May-09","Jun-09","Jul-09","Ago-09","Sep-09","Oct-09","Nov-09","Dic-09","Ene-10","Feb-10","Mar-10","Abr-10","May-10","Jun-10","Jul-10","Ago-10","Sep-10","Oct-10","Nov-10","Dic-10")

```
```{r}
NumeroSismos<-c(Enero95,Febrero95,Marzo95,Abril95,Mayo95,Junio95,Julio95,Agosto95,Septiembre95,Octubre95,Noviembre95,Diciembre95,
                Enero96,Febrero96,Marzo96,Abril95,Mayo96,Junio96,Julio95,Agosto96,Septiembre96,Octubre96,Noviembre96,Diciembre96,
                Enero97,Febrero97,Marzo97,Abril97,Mayo97,Junio97,Julio95,Agosto97,Septiembre97,Octubre97,Noviembre97,Diciembre97,
                Enero98,Febrero98,Marzo98,Abril98,Mayo98,Junio98,Julio98,Agosto98,Septiembre98,Octubre98,Noviembre98,Diciembre98,
                Enero99,Febrero99,Marzo99,Abril99,Mayo99,Junio99,Julio99,Agosto99,Septiembre99,Octubre99,Noviembre99,Diciembre99,
                Enero00,Febrero00,Marzo00,Abril00,Mayo00,Junio00,Julio00,Agosto00,Septiembre00,Octubre00,Noviembre00,Diciembre00,
                Enero01,Febrero01,Marzo01,Abril01,Mayo01,Junio01,Julio01,Agosto01,Septiembre01,Octubre01,Noviembre01,Diciembre01,
                Enero02,Febrero02,Marzo02,Abril02,Mayo02,Junio02,Julio02,Agosto02,Septiembre02,Octubre02,Noviembre02,Diciembre02,
                Enero03,Febrero03,Marzo03,Abril03,Mayo03,Junio03,Julio03,Agosto03,Septiembre03,Octubre03,Noviembre03,Diciembre03,
                Enero04,Febrero04,Marzo04,Abril04,Mayo04,Junio04,Julio04,Agosto04,Septiembre04,Octubre04,Noviembre04,Diciembre04,
                Enero05,Febrero05,Marzo05,Abril05,Mayo05,Junio05,Julio05,Agosto05,Septiembre05,Octubre05,Noviembre05,Diciembre05,
                Enero06,Febrero06,Marzo06,Abril06,Mayo06,Junio06,Julio06,Agosto06,Septiembre06,Octubre06,Noviembre06,Diciembre06,
                Enero07,Febrero07,Marzo07,Abril07,Mayo07,Junio07,Julio07,Agosto07,Septiembre07,Octubre07,Noviembre07,Diciembre07,
                Enero08,Febrero08,Marzo08,Abril08,Mayo08,Junio08,Julio08,Agosto08,Septiembre08,Octubre08,Noviembre08,Diciembre08,
                Enero09,Febrero09,Marzo09,Abril09,Mayo09,Junio09,Julio09,Agosto09,Septiembre09,Octubre09,Noviembre09,Diciembre09,
                Enero10,Febrero10,Marzo10,Abril10,Mayo10,Junio10,Julio10,Agosto10,Septiembre10,Octubre10,Noviembre10,Diciembre10)

```
```{r}
DF %>% rename(Profundidad = `profundidad (km)`, Magnitud = `magnitud (M)`) -> DF
```
# Hallar el promedio

Vamos a hallar la profundidad promedio para cada mes de cada año
```{r}
fechas <- unique(DF$Fecha)
```
Estan todos meses desde enero del año 1995 hasta diciembre de 2010.
Entonces son 16 o 192 meses.
```{r}
Profundidad_prom <- data.frame(Meses=Meses)

# En nuestra data se manejan 16 años o 192 meses
Año95=c()
Año96=c()
Año97=c()
Año98=c()
Año99=c()
Año00=c()
Año01=c()
Año02=c()
Año03=c()
Año04=c()
Año05=c()
Año06=c()
Año07=c()
Año08=c()
Año09=c()
Año10=c()
for(i in 1:16){

  for(j in 1:12){
    DF %>% filter(Fecha == fechas[j*i]) %>% select(Profundidad) %>% sum -> suma
    DF %>% filter(Fecha == fechas[j*i]) %>% select(Profundidad) %>% count -> cantidad
    
    if(i == 1){
      Año95 <- c(Año95, round(suma/cantidad$n,2))
    } else if(i == 2){
      Año96 <- c(Año96, round(suma/cantidad$n,2))
    } else if(i == 3){
      Año97 <- c(Año97, round(suma/cantidad$n,2))
    } else if(i == 4){
      Año98 <- c(Año98, round(suma/cantidad$n,2))
    } else if(i == 5){
      Año99 <- c(Año99, round(suma/cantidad$n,2))
    } else if(i == 6){
      Año00 <- c(Año00, round(suma/cantidad$n,2))
    } else if(i == 7){
      Año01 <- c(Año01, round(suma/cantidad$n,2))
    } else if(i == 8){
      Año02 <- c(Año02, round(suma/cantidad$n,2))
    } else if(i == 9){
      Año03 <- c(Año03, round(suma/cantidad$n,2))
    } else if(i == 10){
      Año04 <- c(Año04, round(suma/cantidad$n,2))
    } else if(i == 11){
      Año05 <- c(Año05, round(suma/cantidad$n,2))
    } else if(i == 12){
      Año06 <- c(Año06, round(suma/cantidad$n,2))
    } else if(i == 13){
      Año07 <- c(Año07, round(suma/cantidad$n,2))
    } else if(i == 14){
      Año08 <- c(Año08, round(suma/cantidad$n,2))
    } else if(i == 15){
      Año09 <- c(Año09, round(suma/cantidad$n,2))
    } else {
      Año10 <- c(Año10, round(suma/cantidad$n,2))
    }
  }
}
```
#Crear array
```{r}
Profundidad_Promedio<-c(Año95,Año96,Año97,Año98,Año99,Año00,Año01,Año02,Año03,Año04,Año05,Año06,Año07,Año08,Año09,Año10)
```
# Para la Magnitud
```{r}
Magnitud_prom <- data.frame(Meses=Meses)

# En nuestra data se manejan 16 años o 192 meses
Año95=c()
Año96=c()
Año97=c()
Año98=c()
Año99=c()
Año00=c()
Año01=c()
Año02=c()
Año03=c()
Año04=c()
Año05=c()
Año06=c()
Año07=c()
Año08=c()
Año09=c()
Año10=c()
for(i in 1:16){

  for(j in 1:12){
    DF %>% filter(Fecha == fechas[j*i]) %>% select(Magnitud) %>% sum -> suma
    DF %>% filter(Fecha == fechas[j*i]) %>% select(Magnitud) %>% count -> cantidad
    
    if(i == 1){
      Año95 <- c(Año95, round(suma/cantidad$n,2))
    } else if(i == 2){
      Año96 <- c(Año96, round(suma/cantidad$n,2))
    } else if(i == 3){
      Año97 <- c(Año97, round(suma/cantidad$n,2))
    } else if(i == 4){
      Año98 <- c(Año98, round(suma/cantidad$n,2))
    } else if(i == 5){
      Año99 <- c(Año99, round(suma/cantidad$n,2))
    } else if(i == 6){
      Año00 <- c(Año00, round(suma/cantidad$n,2))
    } else if(i == 7){
      Año01 <- c(Año01, round(suma/cantidad$n,2))
    } else if(i == 8){
      Año02 <- c(Año02, round(suma/cantidad$n,2))
    } else if(i == 9){
      Año03 <- c(Año03, round(suma/cantidad$n,2))
    } else if(i == 10){
      Año04 <- c(Año04, round(suma/cantidad$n,2))
    } else if(i == 11){
      Año05 <- c(Año05, round(suma/cantidad$n,2))
    } else if(i == 12){
      Año06 <- c(Año06, round(suma/cantidad$n,2))
    } else if(i == 13){
      Año07 <- c(Año07, round(suma/cantidad$n,2))
    } else if(i == 14){
      Año08 <- c(Año08, round(suma/cantidad$n,2))
    } else if(i == 15){
      Año09 <- c(Año09, round(suma/cantidad$n,2))
    } else {
      Año10 <- c(Año10, round(suma/cantidad$n,2))
    }
  }
}
```
#Crear array
```{r}
Magnitud_Promedio<-c(Año95,Año96,Año97,Año98,Año99,Año00,Año01,Año02,Año03,Año04,Año05,Año06,Año07,Año08,Año09,Año10)
```
```{r}
Data=data.frame(Fechas,NumeroSismos,Profundidad_Promedio,Magnitud_Promedio)
```
#Union de tablas
```{r}

DFG<-DFG[,-1]
DataFrame=cbind(Data,DFG)
DF<-DataFrame
```

```{r}
DF$`PROMEDIO ANUAL (MPCD)` <- NA
DF[,-ncol(DF)] -> DF


```


# Convertir a tipo fecha
```{r}
gsub(pattern = "z", replacement = "", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "s", replacement = "", x = DF$Fechas) -> DF$Fechas

gsub(pattern = "z", replacement = "", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "s", replacement = "", x = DF$Fechas) -> DF$Fechas

gsub(pattern = "Ene", replacement = "1", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Feb", replacement = "2", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Mar", replacement = "3", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Abr", replacement = "4", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "May", replacement = "5", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Jun", replacement = "6", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Jul", replacement = "7", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Ago", replacement = "8", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Sep", replacement = "9", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Oct", replacement = "10", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Nov", replacement = "11", x = DF$Fechas) -> DF$Fechas
gsub(pattern = "Dic", replacement = "12", x = DF$Fechas) -> DF$Fechas
as.Date(paste("01",DF$Fechas, sep = "-"), format = "%d-%m-%y") -> DF$Fechas


DF[DF$Fechas < as.Date("1995/1/1"),] <- NA

na.omit(DF) -> DF
```



```{r}
write.table(DataFrame, file = "DataFrame.csv",sep = ",",row.names = F)
```



```{r}
createDD <- function(){
  # Creamos una data vacía con los nombres de las variables
  DD <- data.frame(Dia=NA,AGUAYTIA.Lote.31.C=NA,CNPC.PERU.Lote.X=NA,MONTERRICO.Lote.II=NA,OLYMPIC.Lote.XIII=NA,PETROPERÚ.Lote.I.T.=NA,PLUSPETROL.Lote.56=NA,PLUSPETROL.Lote.88=NA, REPSOL.Lote.57=NA, SAPET.Lote.VII_VI=NA, SAVIA.Lote.Z.2B=NA,UNNA.ENERGIA=NA, UNNA.ENERGIA.1=NA, TOTAL=NA)
  
  meses <- c("January", "February", "March", "April", "May") 
  i <- 1
  
  # Para cada mes agregamos su respectiva data
  for(mes in meses){
    tmp <- read.csv( paste("Datos-Gas/Produccion+gas+m3-", paste(mes, "-2022.csv", sep=""), sep="") )
    # La última fila de totales no nos interesa, entonces la eliminaremos
    tmp[nrow(tmp),] <- NA
    
    # Notamos un error en los nombres, en variable DIA.........AGUAYTIA.Lote.31.C, La última parte de AGUAYTIA.Lote.31.C           debería estar la      variable llamada X, entonces lo cambiaremos.
    tmp %>% rename(
      "Dia" = DIA............AGUAYTIA.Lote.31.C,
      "AGUAYTIA.Lote.31.C" = X) -> tmp
    
    # Pasaremos la fecha a la correspondiente, solo debemos correr una vez este fragmento de código.
    as.Date(paste(tmp$Dia, i, "2022", sep = "-"), format = "%d-%m-%Y") -> tmp$Dia
    
    DD <- add_row(DD, tmp)
    i <- i + 1
  }
  
  return(DD)
}

DD <- createDD()
```

```{r}
DD %>% rename("Fecha" = Dia) -> DD

# Se elimina la última columna de totales
DD<-DD[,-ncol(DD)]
# Se elimina la columna de UNNA.ENERGIA y UNNA.ENERGIA.1 ya que contienen información poco relevante
DD<-DD[,-ncol(DD)]
DD<-DD[,-ncol(DD)]

# Se omiten los NA
na.omit(DD) -> DD
```


```{r}
encodeConnection <- file('DataFrameDiary.csv', encoding = "UTF-8")
write.csv(DD, file = encodeConnection)
```

