---
title: "Limpieza"
output:
  html_document:
    df_print: paged
---

#Limpeza de datos

```{r Lectura de las bases de datos 2019 y 2020 de Cusco}

library(readr)

cusco_19 = read.csv(file="cusco19.csv")

cusco_20 = read.csv(file="cusco20.csv")

# Eliminar observaciones incompletas

cusco_19  = na.omit(cusco_19)

cusco_20  = na.omit(cusco_20)

```


## Base de datos con todas las observaciones y las variables necesarias

```{r Base de datos con las variables seleccionadas}

# UNIÓN DE LA BASE DE DATOS DEL 2019 Y DEL 2020

departamento = c(cusco_19$DepartamentoPN, cusco_20$DepartamentoPN)
red = c(cusco_19$Red, cusco_20$Red)
sexo = c(cusco_19$Sexo, cusco_20$Sexo)
edad = c(cusco_19$EdadMeses, cusco_20$EdadMeses)
hemoglobina = c(cusco_19$Hemoglobina, cusco_20$Hemoglobina)
estado_de_anemia = c(cusco_19$Dx_Anemia, cusco_20$Dx_Anemia)
provincia = c(cusco_19$PROVINCIA, cusco_20$ProvinciaPN)
IMC = c(cusco_19$IMC, cusco_20$IMC)
fecha = c(cusco_19$FechaAtencion, cusco_20$FechaAtencion)

library(tidyverse)
library(lubridate)

# SEPARACIÓN DE LA VARIABLE FECHA POR LAS VARIABLES MES Y AÑO DE ATENCIÓN

mes = c()
agnio = c()

for (i in 1:length(fecha)){
  date <- as.Date(fecha[i], '%m/%d/%Y')
  mes[i] <- as.numeric(format(date, '%m'))
  agnio[i] <- as.numeric(format(date, '%Y'))
}


cusco = data.frame(departamento, provincia, red, sexo, edad, IMC, hemoglobina, estado_de_anemia, mes, agnio)
cusco = cusco[cusco$departamento == 'CUSCO', ]
cusco$IMC <- round(as.numeric(cusco$IMC), 2)
cusco = cusco[cusco$IMC<50,]
cusco
```

```{r Exportar csv}

write.csv(cusco, file = "cusco.csv")

```


