---
title: "DESCRIPTORES GRÁFICOS"
output: html_notebook
---
```{r}
DF <- read.csv(" ")
```

```{r}
library("readr") #Para leer archivos
library("dplyr") #El pipe %>%
library("stringr") #Para caracteres
library("modeest") #Para la moda
```

#PARÁMETROS 
main="título"
sub="título de abajo"
lty=n Tipo de Línea
xlab="Nombre del eje x"
ylab="Nombre del eje y"
xlim=c(xminimo, xmaximo)
ylim=c(yminimo, ymaximo)


#GRÁFICOS ESTADÍSTICOS UNIVARIABLES:

**1) UNIDIMENSIONALES**

```{r}
barplot(DF$Largo, main= " ", sub = " ", lty = 2,  xlab = " ", ylab =" " )
```



```{r}
largo <- (DF$Largo)
boxplot(largo[1], largo[2], largo[3],largo[4], range = 2,boxwex = 1, width =NULL,plot = TRUE, varwidth = TRUE, notch=TRUE,col = NULL,pars = NULL, horizontal = FALSE,add = FALSE, main =" ", xlab = " ", ylab = " ")
```


```{r}
hist(DF$Largo, include.lowest = TRUE, right = TRUE, col = NULL, border = par("fg"), main = paste("HISTOGRAMA DE" , " "), xlab = " ", ylab = " ")
```

```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```








