<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Proyecto de Estadistica</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="S7_Informe_files/libs/clipboard/clipboard.min.js"></script>
<script src="S7_Informe_files/libs/quarto-html/quarto.js"></script>
<script src="S7_Informe_files/libs/quarto-html/popper.min.js"></script>
<script src="S7_Informe_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="S7_Informe_files/libs/quarto-html/anchor.min.js"></script>
<link href="S7_Informe_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="S7_Informe_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="S7_Informe_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="S7_Informe_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="S7_Informe_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proyecto de Estadistica</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="tema-pg---estadística" class="level1">
<h1>Tema PG - Estadística</h1>
<section id="tema" class="level2">
<h2 class="anchored" data-anchor-id="tema">Tema :</h2>
<section id="analizando-los-concesionarios-del-comedor-principal-en-utec-desde-el-2022-1-hasta-el-2023-1" class="level3">
<h3 class="anchored" data-anchor-id="analizando-los-concesionarios-del-comedor-principal-en-utec-desde-el-2022-1-hasta-el-2023-1">Analizando los concesionarios del comedor principal en UTEC desde el 2022-1 hasta el 2023-1 :</h3>
<p>Nosotros estamos interesados en saber el grado de satisfacción que presentan los alumnos y personal de UTEC frente al cambio de concesionario del comedor principal ubicado en piso 2 de la universidad.</p>
</section>
</section>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción:</h2>
<p>En el segundo piso de UTEC se encuentra el comedor, espacio en el que hay una concesionaria encargada de vender almuerzos a alumnos y personal de la universidad, aprovechando la conveniencia de ubicarse dentro de esta. Este servicio es de gran importancia, pues es la principal fuente de alimentación de muchos alumnos de la universidad.</p>
</section>
<section id="relevancia" class="level2">
<h2 class="anchored" data-anchor-id="relevancia">Relevancia:</h2>
<p>Este estudio fue realizado principalmente por la motivación de querer conocer la opinión de los usuarios sobre la cafetería en UTEC. Para profundizar el análisis, se ha decidido recolectar igualmente datos adicionales a la opinión, e igualmente se han recolectado datos sobre la concesionaria del ciclo previo (2022-2).</p>
</section>
<section id="objetivos" class="level2">
<h2 class="anchored" data-anchor-id="objetivos">Objetivos :</h2>
<section id="objetivo-principal" class="level4">
<h4 class="anchored" data-anchor-id="objetivo-principal">Objetivo principal :</h4>
<ul>
<li>Conocer el nivel de satisfacción del servicio en el comedor de UTEC en base a la opinión de los alumnos.</li>
</ul>
</section>
<section id="objetivo-secundarios" class="level4">
<h4 class="anchored" data-anchor-id="objetivo-secundarios">Objetivo Secundarios :</h4>
<ul>
<li>Analizar los variables en busca de patrones que ayuden al estudio.</li>
</ul>
<!-- -->
<ul>
<li><p>Verificar si los estudiantes están contentos con el servicio actual.</p></li>
<li><p>Comparar la opinión de usuarios, con respecto al concesionario actual y al anterior.</p></li>
<li><p>Ayudar a conseguir una mejora en la experiencia de los usuarios.</p></li>
</ul>
</section>
</section>
<section id="limpieza-de-la-base-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="limpieza-de-la-base-de-datos">Limpieza de la base de datos :</h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.1.3</code></pre>
</div>
</div>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>Limpiando la variable carrera :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>carrera <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"IngenieríaMecatronica."</span>, <span class="st">"Ingeniería Mecatronica"</span>, DF<span class="sc">$</span>carrera)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Limpiando ‘presupuesto’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>presupuesto <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"10 a 30 soles"</span>, <span class="st">"20"</span>, DF<span class="sc">$</span>presupuesto)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>presupuesto <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"30 a 50 soles"</span>, <span class="st">"40"</span>, DF<span class="sc">$</span>presupuesto)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>presupuesto <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"50 a 70 soles"</span>, <span class="st">"60"</span>, DF<span class="sc">$</span>presupuesto)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>presupuesto <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"70 a 90 soles"</span>, <span class="st">"80"</span>, DF<span class="sc">$</span>presupuesto)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>presupuesto <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"90 soles a mas"</span>, <span class="st">"100"</span>, DF<span class="sc">$</span>presupuesto)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>presupuesto <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(DF<span class="sc">$</span>presupuesto)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(DF<span class="sc">$</span>presupuesto)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  5   7   8  10  13  15  18  20  25  30  40  45  50  52  60  65  70  75  80 100 
  1   1   1   6   1   1   1  14   3   1  10   1  13   1  13   1   2   2   1   9 
120 150 170 230 300 500 
  4   3   1   1   1   1 </code></pre>
</div>
</div>
<p>Limpiando ‘tiempo_espera’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_espera <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"5 a 10 minutos"</span>, <span class="dv">7</span>, DF<span class="sc">$</span>tiempo_espera)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_espera <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"10 a 15 minutes"</span>, <span class="dv">12</span>, DF<span class="sc">$</span>tiempo_espera)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_espera <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"15 a 20 minutos"</span>, <span class="dv">17</span>, DF<span class="sc">$</span>tiempo_espera)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_espera <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(DF<span class="sc">$</span>tiempo_espera)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(DF<span class="sc">$</span>tiempo_espera)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2  3  5  7  8 10 12 13 15 17 20 25 30 40 80 
 1  1  1 10 15  1 14 13  1  7  4 16  1  7  1  1 </code></pre>
</div>
</div>
<p>Limpiando ‘tiempo_disponible’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_disponible <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"20 minutos"</span>, <span class="dv">20</span>, DF<span class="sc">$</span>tiempo_disponible)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_disponible <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"40 minutos"</span>, <span class="dv">20</span>, DF<span class="sc">$</span>tiempo_disponible)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_disponible <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"1 hora"</span>, <span class="dv">60</span>, DF<span class="sc">$</span>tiempo_disponible)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_disponible <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"1 hora a mas"</span>, <span class="st">""</span>, DF<span class="sc">$</span>tiempo_disponible)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_disponible <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"60 a mas"</span>, <span class="st">""</span>, DF<span class="sc">$</span>tiempo_disponible)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>tiempo_disponible <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(DF<span class="sc">$</span>tiempo_disponible)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(DF<span class="sc">$</span>tiempo_disponible)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 20  25  30  35  40  45  50  60 100 120 360 
 19   4  15   3   7   5   5  32   1   1   1 </code></pre>
</div>
</div>
<p>Corrigiendo el tipo de valor de ‘ciclo’, ‘consumo_semanal_actual’, y ‘consumo_semanal_anterior’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>consumo_semanal_actual <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(DF<span class="sc">$</span>consumo_semanal_actual)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>consumo_semanal_previo <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(DF<span class="sc">$</span>consumo_semanal_previo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Rellenando algunos SI faltantes en si consumen actualmente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>consume_actualmente[<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>]<span class="ot">&lt;-</span><span class="st">"Sí"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Limpiando datos vacíos en precio actual y previo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>precio_actual[DF<span class="sc">$</span>precio_actual <span class="sc">==</span> <span class="st">''</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>precio_previo[DF<span class="sc">$</span>precio_previo <span class="sc">==</span> <span class="st">''</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="análisis-descriptivo" class="level2">
<h2 class="anchored" data-anchor-id="análisis-descriptivo">Análisis descriptivo :</h2>
</section>
<section id="análisis-de-la-concesionaria-actual" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-la-concesionaria-actual">Análisis de la concesionaria actual :</h2>
</section>
<section id="gráfico-1" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-1">Gráfico 1:</h2>
</section>
<section id="descriptores-numéricos-del-tiempo-de-espera" class="level2">
<h2 class="anchored" data-anchor-id="descriptores-numéricos-del-tiempo-de-espera">Descriptores numéricos del tiempo de espera</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(DF<span class="sc">$</span>tiempo_espera)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   1.00    7.00   12.00   14.11   20.00   80.00      60 </code></pre>
</div>
</div>
<p>Coeficiente de variación</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sd</span>(DF<span class="sc">$</span>tiempo_espera,<span class="at">na.rm =</span> <span class="cn">TRUE</span>)<span class="sc">/</span><span class="fu">mean</span>(DF<span class="sc">$</span>tiempo_espera, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.73</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(DF<span class="sc">$</span>tiempo_espera, <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">"Tiempo de espera"</span>, <span class="at">xlab =</span> <span class="st">"Tiempo (min)"</span>, <span class="at">outpch =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="análisis-gráfico-1" class="level4">
<h4 class="anchored" data-anchor-id="análisis-gráfico-1">Análisis gráfico 1:</h4>
<p>Para esta variable numérica, hacemos uso de los descriptores numéricos para un mejor análisis, como podemos apreciar la mayoría de datos se encuentran entre 7 y 20 min y contamos con solo 2 datos atípicos, ahora nuestro coeficiente de variación es 0.73, por lo tanto no podemos hacer uso de la media debido a que es muy elevado, pero usando la mediana podemos decir que la mitad de los datos se ubica en 12 min.</p>
</section>
</section>
<section id="gráfico-2" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-2">Gráfico 2 :</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(DF<span class="sc">$</span>tiempo_disponible, <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">"Tiempo disponible"</span>, <span class="at">xlab =</span> <span class="st">"Tiempo (min)"</span>, <span class="at">outpch =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="análisis-gráfico-2" class="level3">
<h3 class="anchored" data-anchor-id="análisis-gráfico-2">Análisis gráfico 2:</h3>
<section id="gráfico" class="level4">
<h4 class="anchored" data-anchor-id="gráfico">Gráfico :</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaicplot</span>(DF<span class="sc">$</span>ciclo <span class="sc">~</span> DF<span class="sc">$</span>consume_actualmente,<span class="at">main=</span><span class="st">"Relacion entre el ciclo y si consume o no en el comedor"</span>,<span class="at">color=</span><span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>, )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="análisis-gráfico-2-1" class="level4">
<h4 class="anchored" data-anchor-id="análisis-gráfico-2-1">Análisis gráfico 2:</h4>
<p>En esta gráfica analizamos la relación entre el ciclo cursado por los estudiantes y si consumen o no en la cafetería. Podemos observar que de la muestra observada, los estudiantes de tercer, cuarto y quinto ciclo son aquellos que acuden más a la cafetería actualmente, e igualmente conforman la mayor parte de la muestra.</p>
</section>
</section>
</section>
<section id="análisis-de-ambas-concesionarias" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-ambas-concesionarias">Análisis de ambas concesionarias</h2>
</section>
<section id="gráfico-3" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-3">Gráfico 3 :</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>menu_previo[DF<span class="sc">$</span>menu_previo <span class="sc">==</span> <span class="st">''</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>menu_actual[DF<span class="sc">$</span>menu_actual <span class="sc">==</span> <span class="st">''</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span><span class="fu">filter</span>(consumio_previo<span class="sc">==</span><span class="st">"Si"</span> <span class="sc">&amp;</span> consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>) <span class="ot">-&gt;</span>barplot4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="cantidad-de-alumnos-que-consumían-en-ambas-concesionarias" class="level3">
<h3 class="anchored" data-anchor-id="cantidad-de-alumnos-que-consumían-en-ambas-concesionarias">Cantidad de alumnos que consumían en ambas concesionarias</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(barplot4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(barplot4<span class="sc">$</span>menu_previo),<span class="at">main=</span><span class="st">"Consumo en ambas consesionarios"</span>,<span class="at">cex.names =</span> <span class="fl">0.8</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">70</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">grid</span>(<span class="at">nx =</span> <span class="cn">NA</span>, <span class="at">ny =</span> <span class="cn">NULL</span>, <span class="at">lwd =</span> <span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"gray"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="análisis-gráfico-3" class="level4">
<h4 class="anchored" data-anchor-id="análisis-gráfico-3">Análisis gráfico 3 :</h4>
<p>Para elaborar este gráfico se busco seleccionar a las personas que consumían anteriormente y que consumen actualmente, y de igual forma se puede apreciar que el menú mas consumido sigue siendo el estudiantil.</p>
</section>
</section>
</section>
<section id="gráfico-4" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-4">Gráfico 4 :</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>precio_actual <span class="ot">&lt;-</span> <span class="fu">factor</span>(DF<span class="sc">$</span>precio_actual, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Terrible"</span>, <span class="st">"Mal"</span>, <span class="st">"Regular"</span>, <span class="st">"Bien"</span>, <span class="st">"Muy Bien"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>precio_previo <span class="ot">&lt;-</span> <span class="fu">factor</span>(DF<span class="sc">$</span>precio_previo, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Terrible"</span>, <span class="st">"Mal"</span>, <span class="st">"Regular"</span>, <span class="st">"Bien"</span>, <span class="st">"Muy Bien"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(precio_previo) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">n</span>()) <span class="ot">-&gt;</span> PP</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>DF <span class="sc">%&gt;%</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(precio_actual) <span class="sc">%&gt;%</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(<span class="fu">n</span>()) <span class="ot">-&gt;</span> PA</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>PP <span class="ot">&lt;-</span> PP[<span class="sc">-</span><span class="fu">nrow</span>(PP), ]</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>PA <span class="ot">&lt;-</span> PA[<span class="sc">-</span><span class="fu">nrow</span>(PA), ]</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>PJ <span class="ot">&lt;-</span> <span class="fu">cbind</span>(PP, PA)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(PJ) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pp"</span>, <span class="st">"ppn"</span>, <span class="st">"pa"</span>, <span class="st">"pan"</span>)</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">t</span>(<span class="fu">as.matrix</span>(PJ[, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>)])) ,<span class="at">col =</span> <span class="fu">c</span>(<span class="st">"#0DADFC"</span>, <span class="st">"darkblue"</span>), <span class="at">beside =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">"Consideración del precio en el comedor"</span>, <span class="at">names.arg =</span> <span class="fu">levels</span>(PJ<span class="sc">$</span>pp))</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="fu">c</span>(<span class="st">"Precio concesionaria anterior"</span>, <span class="st">"Precio concesionaria actual"</span>), <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"#0DADFC"</span>, <span class="st">"darkblue"</span>), <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="análisis-gráfico-4" class="level4">
<h4 class="anchored" data-anchor-id="análisis-gráfico-4">Análisis gráfico 4:</h4>
<p>Como podemos apreciar en este gráfico, podemos ver como hay una mayor cantidad de gente que considera que los precios actuales del comedor son malos y terribles, sin embargo también los consideran mas regulares, en cambio el comedor anterior tiene mas valoraciones de bien y muy bien que el actual</p>
</section>
</section>
<section id="gráfico-5" class="level2">
<h2 class="anchored" data-anchor-id="gráfico-5">Gráfico 5:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>cyl_table <span class="ot">&lt;-</span> <span class="fu">table</span>(DF<span class="sc">$</span>consume_actualmente)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>gear_table <span class="ot">&lt;-</span> <span class="fu">table</span>(DF<span class="sc">$</span>consumio_previo)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">rbind</span>(cyl_table,gear_table), <span class="at">beside=</span><span class="cn">TRUE</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="fu">c</span>(<span class="st">"royalblue"</span>,<span class="st">"red"</span>), <span class="at">main=</span><span class="st">"Consumo en los consecionarios"</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">"Consumo"</span>, <span class="at">ylab=</span><span class="st">"Frecuencia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in rbind(cyl_table, gear_table): number of columns of result is not a
multiple of vector length (arg 2)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Actual"</span>, <span class="st">"Previo"</span>), <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"royalblue"</span>, <span class="st">"red"</span>), </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Leyenda"</span>)                                                     </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="análisis-gráfico-5" class="level3">
<h3 class="anchored" data-anchor-id="análisis-gráfico-5">Análisis gráfico 5:</h3>
<p>A partir de esta comparación entre la variable consumen actualmente y previo, se obtiene que la proporción de personas encuestadas que consumen ahora es 95 menor que la proporción de personas encuestadas que consumían antes 104 y la proporción de personas encuestadas que no consumen ahora 60 es mayor que la proporción de personas encuestadas que no consumían antes 51. Esto podría ser un indicador de que la nueva concesionaria tiene menos clientes en comparación con la anterior concesionaria resaltando una preferencia mayor de los consumidores del comedor por esta ultima .</p>
</section>
</section>
<section id="conclusiones" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones">Conclusiones :</h2>
<p>Mediante el análisis descriptivo realizado en el desarrollo, obtuvimos varias conclusiones justificables mediante nuestros gráficos. Donde pudimos despejar varias incógnitas como la ¿A que ciclo pertenecen los estudiantes mas recurrentes?,¿Cual es la principal razón por el que no consumen?, ¿Cual es el tiempo de espera?, entre otros. Con los gráficos recopilados podemos ver las debilidades como las fortalezas de la concesionario actual, compararlas con la anterior. Finalmente con el análisis podemos presentar posibles oportunidades de mejora a la administración de UTEC para que la cafetería pueda brindar un optimo servicio.</p>
</section>
<section id="probabilidades" class="level2">
<h2 class="anchored" data-anchor-id="probabilidades">Probabilidades:</h2>
<section id="probabilidad-empírica" class="level3">
<h3 class="anchored" data-anchor-id="probabilidad-empírica">Probabilidad empírica</h3>
<section id="variable-aleatoria-x" class="level4">
<h4 class="anchored" data-anchor-id="variable-aleatoria-x">Variable aleatoria X</h4>
<p>Se realiza un experimento, donde se extrae un estudiante/personal de UTEC al azar, y se observa si consume o no en la cafetería en el presente ciclo 2023-1. Nos quedamos con una variable aleatoria versátil que se puede relacionar con cualquier parte del estudio, para relacionar otros datos con el hecho de que consuman o no en la cafetería.</p>
<p><span class="math display">\[
\mathbb{X}=
\begin{cases}
1 &amp; \text{Consume en la cafetería actualmente}\\
0 &amp; \text{No consume en la cafetería actualmente}\\
\end{cases}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># FALTA MUESTRAS ESPACIO MUESTRAL</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>))</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>x0 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"No"</span>))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>xtotal <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DF)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidad de cada evento atómico</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>xtotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 154</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>x1<span class="sc">/</span>xtotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0974026</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>x0<span class="sc">/</span>xtotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3896104</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobando atomicidad</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>(x1<span class="sc">+</span>x0)<span class="sc">/</span>xtotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.487013</code></pre>
</div>
</div>
<p>Espacio de resultados teórico y probabilidad empírica de cada evento atómico:</p>
<p>A1: Consume en la cafetería actualmente:<br>
<span class="math display">\[
\mathbb{S} = \{Sí\}
\]</span></p>
<p><span class="math display">\[
\mathbb{P}(A1):
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0974026</code></pre>
</div>
</div>
<p>A2: No consume en la cafetería actualmente:</p>
<p><span class="math display">\[
\mathbb{S} = \{No\}
\]</span></p>
<p><span class="math display">\[
\mathbb{P}(A2):
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"No"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3896104</code></pre>
</div>
</div>
</section>
<section id="variable-aleatoria-y" class="level4">
<h4 class="anchored" data-anchor-id="variable-aleatoria-y">Variable aleatoria Y</h4>
<p>Se realiza un experimento, donde se elige a una persona en UTEC que consume en la cafetería en el presente ciclo 2023-1, y se observa el tiempo de espera que ha reportado para comer en la cafetería. Nos quedamos con una variable aleatoria que clasifica los tiempos de espera reportado según si se consideran óptimos (menos de 5), aceptable (entre 5 y 15), o excesivo (15 o más), la cual se puede relacionar con demás aspectos del estudio.</p>
<p><span class="math display">\[
\mathbb{Y}=
\begin{cases}
1 &amp; \text{Su tiempo de espera es mayor o igual a 0 minutos, y menor a 5}\\
2 &amp; \text{Su tiempo de espera es mayor o igual a 5 minutos, y menor a 15}\\
3 &amp; \text{Su tiempo de espera es mayor o igual a 15}\\
\end{cases}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ESPACIO MUESTRAL</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span> <span class="sc">&amp;</span> tiempo_espera <span class="sc">&lt;</span> <span class="dv">5</span>))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span> <span class="sc">&amp;</span> tiempo_espera <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> tiempo_espera <span class="sc">&lt;</span> <span class="dv">15</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>y3 <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span> <span class="sc">&amp;</span> tiempo_espera <span class="sc">&gt;=</span> <span class="dv">15</span>))</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>ytotal <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>))</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidad de cada evento atómico</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>ytotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>y1<span class="sc">/</span>ytotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>y2<span class="sc">/</span>ytotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9333333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>y3<span class="sc">/</span>ytotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06666667</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobando atomicidad</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>(y1<span class="sc">+</span>y2<span class="sc">+</span>y3)<span class="sc">/</span>ytotal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Espacio de resultados teórico y probabilidad empírica de cada evento atómico:</p>
<p>B1: El tiempo de espera es mayor o igual a 0 minutos, y menor a 5:</p>
<p><span class="math display">\[
\mathbb{S}=[0,5[
\]</span></p>
<p><span class="math display">\[
\mathbb{P}(B1):
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span> <span class="sc">&amp;</span> tiempo_espera <span class="sc">&lt;</span> <span class="dv">5</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Tiempo de espera mayor o igual a 5 minutos, y menor a 15:</p>
<p><span class="math display">\[
\mathbb{S}= [5,15[
\]</span></p>
<p><span class="math display">\[
\mathbb{P}(B2):
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span> <span class="sc">&amp;</span> tiempo_espera <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> tiempo_espera <span class="sc">&lt;</span> <span class="dv">15</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9333333</code></pre>
</div>
</div>
<p>Tiempo de espera mayor o igual a 15:</p>
<p><span class="math display">\[
\mathbb{S}=[15,+\infty[
\]</span></p>
<p><span class="math display">\[
\mathbb{P}(B3):
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span> <span class="sc">&amp;</span> tiempo_espera <span class="sc">&gt;=</span> <span class="dv">15</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06666667</code></pre>
</div>
</div>
</section>
</section>
<section id="probabilidad-condicional" class="level3">
<h3 class="anchored" data-anchor-id="probabilidad-condicional">Probabilidad condicional</h3>
</section>
<section id="independientes" class="level3">
<h3 class="anchored" data-anchor-id="independientes">Independientes:</h3>
<p>Sabemos que para determinar que dos eventos son independientes se debe cumplir:</p>
<p><span class="math display">\[\mathbb{}P(A∩B)=P(A)*P(B)\]</span></p>
<p>Definiendo a mis Eventos A y B:</p>
<p>A= Escoger a una persona el cual pertenezca al sexto ciclo.</p>
<p>B= Escoger a una persona consuma el menú Ejecutivo actual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">6</span> <span class="sc">&amp;</span> menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span> <span class="sc">&amp;</span> rol<span class="sc">==</span><span class="st">"Alumno"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07142857</code></pre>
</div>
</div>
<p>Mediante el uso de filter obtenemos la probabilidad empírica de nuestra intersección, para comprobar si nuestras dos variables son independientes debemos obtener un resultado similar al multiplicar la probabilidad de cada uno.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1372549</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">6</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07843137</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">6</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01076509</code></pre>
</div>
</div>
<p>Halla la probabilidad de A y luego de B,posteriormente las multiplicamos.</p>
<p>Como podemos observar, las probabilidades de la intersección son similares, lo que nos informa que las variables aleatorias del ciclo al que pertenecen cada alumno son independientes al menú que consumen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">1</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">2</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">3</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">4</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">5</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">6</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">7</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">8</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">9</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Ejecutivo"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">10</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)))<span class="ot">-&gt;</span>ejecu  </span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">1</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">2</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">3</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">4</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">5</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-19"><a href="#cb64-19" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">6</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">7</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">8</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">9</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">10</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)))<span class="ot">-&gt;</span>estudia </span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-26"><a href="#cb64-26" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">1</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-27"><a href="#cb64-27" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">2</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-28"><a href="#cb64-28" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">3</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-29"><a href="#cb64-29" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">4</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-30"><a href="#cb64-30" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">5</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-31"><a href="#cb64-31" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">6</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-32"><a href="#cb64-32" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">7</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-33"><a href="#cb64-33" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">8</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-34"><a href="#cb64-34" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">9</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)),<span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Economico"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>))<span class="sc">*</span></span>
<span id="cb64-35"><a href="#cb64-35" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ciclo<span class="sc">==</span><span class="dv">10</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(rol<span class="sc">==</span><span class="st">"Alumno"</span>)))<span class="ot">-&gt;</span>econo  </span>
<span id="cb64-36"><a href="#cb64-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-37"><a href="#cb64-37" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(econo,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">"blue"</span>,<span class="at">main=</span><span class="st">"Menús"</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">xlab=</span><span class="st">"Ciclo"</span>,<span class="at">ylab=</span><span class="st">"Probabilidad de que su menú sea x"</span>,<span class="at">las=</span><span class="dv">1</span>,<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.15</span>))</span>
<span id="cb64-38"><a href="#cb64-38" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(estudia, <span class="at">type=</span><span class="st">"l"</span>,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">"red"</span>,<span class="at">main=</span><span class="st">"Menu Estudiantil"</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">xlab=</span><span class="st">"Ciclo"</span>,<span class="at">ylab=</span><span class="st">"Probabilidad de que su menu sea Estudiantil"</span>,<span class="at">las=</span><span class="dv">1</span>)</span>
<span id="cb64-39"><a href="#cb64-39" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ejecu, <span class="at">type=</span><span class="st">"l"</span>,<span class="at">pch=</span><span class="dv">16</span>,<span class="at">col=</span><span class="st">"orange"</span>,<span class="at">main=</span><span class="st">"Menu Ejecutivo"</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">xlab=</span><span class="st">"Ciclo"</span>,<span class="at">ylab=</span><span class="st">"Probabilidad de que su menu sea ejecutivo"</span>,<span class="at">las=</span><span class="dv">1</span>)</span>
<span id="cb64-40"><a href="#cb64-40" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>,<span class="at">fill=</span><span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"red"</span>,<span class="st">"orange"</span>),<span class="at">legend=</span><span class="fu">c</span>(<span class="st">"Económico"</span>,<span class="st">"Estudiantil"</span>,<span class="st">"Ejecutivo"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="dependientes" class="level3">
<h3 class="anchored" data-anchor-id="dependientes">Dependientes:</h3>
<p>Deseamos saber cual es la probabilidad de que una persona escoa el menú Estudiantil dado que consume actualmente.</p>
<p>C=Escoger una persona y su menú es el estudiantil.</p>
<p>D=Escoger una persona y este consume actualmente.</p>
<p>Deseamos saber la intersección de los dos eventos.Entonces aplicamos la formula de la condicional.</p>
<p><span class="math display">\[
\mathbb{}P(C∩D)=P(C|D)*P(D)=P(D|C)*P(C)
\]</span></p>
<p>Hallamos la probabilidad de C y D.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF)<span class="ot">-&gt;</span>C</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF)<span class="ot">-&gt;</span>D</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hallamos la siguiente expresión:</p>
<p><span class="math inline">\(P(C|D)*P(D)\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>))<span class="sc">*</span>D</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3311688</code></pre>
</div>
</div>
<p>Hallamos la siguiente expresión:</p>
<p><span class="math inline">\(P(D|C)*P(C)\)</span></p>
<p>Primero hallamos <span class="math inline">\(P(D|C)\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2941176</code></pre>
</div>
</div>
<p>Podemos ver que la probabilidad de P(B|A) es mayor a 1, esto nos quiere decir que el espacio maestral de A esta incluido dentro de D, lo consideramos como 1, ya que si el evento D sucede se da por hecho que el C ha sucedido</p>
<p>Entonces nos queda:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">*</span>C</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3311688</code></pre>
</div>
</div>
<p>Lo cual es similar al filtrar los datos,usando como el denominador el espacio muestral completo de DF :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consume_actualmente<span class="sc">==</span><span class="st">"Sí"</span> <span class="sc">&amp;</span> menu_actual<span class="sc">==</span><span class="st">"Estudiantil"</span>))<span class="sc">/</span><span class="fu">nrow</span>(DF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05844156</code></pre>
</div>
</div>
<p>Podemos ver que nuestra igualdad cumple. Por lo que nuestros eventos son dependientes.Ademas también lo podemos verificar ya que la probabilidad de su intersección no es igual a la multiplicación de cada una.</p>
<p>Se cumple la siguiente expresión <span class="math inline">\(P(C∩D)≠P(C)*P(D)\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>C<span class="sc">*</span>D</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0322567</code></pre>
</div>
</div>
</section>
<section id="tiempo-de-espera-variable-continua" class="level3">
<h3 class="anchored" data-anchor-id="tiempo-de-espera-variable-continua">TIEMPO DE ESPERA: Variable continua</h3>
<p><span class="math inline">\(X \sim Gamma(\alpha,\lambda)\)</span></p>
<p>Para hallar los valores de α y λ realizaremos un sistema de ecuaciones con los datos que obtenemos de R, sabemos que la varianza tiene valor de 105.9671 y la media tiene valor de 14.10638. Remplazaremos en el siguiente sistema de ecuaciones:</p>
<table class="table">
<tbody>
<tr class="odd">
<td><span class="math inline">\(E(X)=\frac{\alpha}{\lambda}\)</span></td>
<td>MEDIA = 14.10638.</td>
</tr>
<tr class="even">
<td><span class="math inline">\(Var(X)=\frac{\alpha}{\lambda^2}\)</span></td>
<td>VARIANZA = 105.9671</td>
</tr>
</tbody>
</table>
<p>Obtenemos los valore α y λ, estos valores solo son parámetros de la función gamma</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(DF<span class="sc">$</span>tiempo_espera,<span class="at">na.rm=</span>T)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.10638</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(DF<span class="sc">$</span>tiempo_espera,<span class="at">na.rm=</span>T) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 105.9671</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>alf<span class="ot">&lt;-</span><span class="fl">14.10638</span><span class="sc">*</span><span class="fl">14.10638</span><span class="sc">/</span> <span class="fl">105.9671</span> </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>lamb<span class="ot">&lt;-</span><span class="fl">14.10638</span><span class="sc">/</span> <span class="fl">105.9671</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora realizamos el histograma y la línea de densidad de la variable <strong>TIEMPO DE ESPERA</strong> y añadimos la curva de la función gamma con los parámetros encontrados en el ítem anterior. En donde podemos observar que estas dos curvas son similares</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(DF<span class="sc">$</span>tiempo_espera, <span class="at">breaks =</span> <span class="dv">22</span>, <span class="at">freq =</span> <span class="cn">FALSE</span>, <span class="at">main =</span> <span class="st">"Histograma de la variabletiempo de espera"</span>, <span class="at">xlab =</span> <span class="st">"tiempo de espera"</span>, <span class="at">col =</span> <span class="st">"darkorange3"</span>)  </span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(DF<span class="sc">$</span>tiempo_espera, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dgamma</span>(x,<span class="fl">14.10638</span><span class="sc">*</span><span class="fl">14.10638</span><span class="sc">/</span> <span class="fl">105.9671</span>,<span class="fl">14.10638</span><span class="sc">/</span> <span class="fl">105.9671</span>),<span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">add =</span> T) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ahora cómo verificamos que en realidad sigue la distribución Gamma. Generaremos una muestra aleatoria de 500 observaciones con la función gamma utilizando la librería <strong>gamlss</strong> para poder realizar la simulación</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gamlss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gamlss' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: splines</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: gamlss.data</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gamlss.data'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:datasets':

    sleep</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: gamlss.dist</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gamlss.dist' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'MASS' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: nlme</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'nlme'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    collapse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: parallel</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> **********   GAMLSS Version 5.4-12  ********** </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>For more on GAMLSS look at https://www.gamlss.com/</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type gamlssNews() to see new features/changes/bug fixes.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">500</span> </span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>) </span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>ma <span class="ot">&lt;-</span> <span class="fu">rGA</span>(<span class="at">n=</span>n, <span class="at">mu=</span>alf, <span class="at">sigma=</span>lamb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora usaremos la función <em>fitDist</em></p>
<p>Ahora usaremos la función&nbsp;<code>fitDist</code>&nbsp;con&nbsp;<code>type='realplus'</code>&nbsp;ya que nuestra muestra aleatoria tiene valores en&nbsp;los reales positivos. Los resultados lo almacenaremos en la variable <code>contenedor</code> y para obtener la lista de los mejores modelos con su respectivo AIC lo calcularemos mediante<code>contenedor$fits</code> .</p>
<p>La función&nbsp;<code>fitDist</code>&nbsp;del paquete&nbsp;<strong>gamlss</strong>&nbsp; nos permite explorar cuales son las mejores distribuciones que puede explicar nuestra muestra aleatoria creada.</p>
<p>AIC: es una medidas de calidad para un conjunto de datos, a menor valor de AIC mejor es el modelo candidato a estudiar</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>contenedor <span class="ot">&lt;-</span> <span class="fu">fitDist</span>(<span class="at">y=</span>ma, <span class="at">type=</span><span class="st">'realplus'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |===                                                                   |   4%
  |                                                                            
  |======                                                                |   9%
  |                                                                            
  |=========                                                             |  13%
  |                                                                            
  |============                                                          |  17%</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in MLE(ll2, start = list(eta.mu = eta.mu, eta.sigma = eta.sigma), :
possible convergence problem: optim gave code=1 false convergence (8)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |===============                                                       |  22%
  |                                                                            
  |==================                                                    |  26%
  |                                                                            
  |=====================                                                 |  30%
  |                                                                            
  |========================                                              |  35%
  |                                                                            
  |===========================                                           |  39%
  |                                                                            
  |==============================                                        |  43%</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in MLE(ll2, start = list(eta.mu = eta.mu, eta.sigma = eta.sigma), :
possible convergence problem: optim gave code=1 false convergence (8)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |=================================                                     |  48%</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in MLE(ll2, start = list(eta.mu = eta.mu, eta.sigma = eta.sigma), :
possible convergence problem: optim gave code=1 false convergence (8)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |=====================================                                 |  52%</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in MLE(ll2, start = list(eta.mu = eta.mu, eta.sigma = eta.sigma), :
possible convergence problem: optim gave code=1 false convergence (8)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
  |                                                                            
  |========================================                              |  57%
  |                                                                            
  |===========================================                           |  61%
  |                                                                            
  |==============================================                        |  65%
  |                                                                            
  |=================================================                     |  70%
  |                                                                            
  |====================================================                  |  74%
  |                                                                            
  |=======================================================               |  78%
  |                                                                            
  |==========================================================            |  83%Error in solve.default(oout$hessian) : 
  Lapack routine dgesv: system is exactly singular: U[4,4] = 0

  |                                                                            
  |=============================================================         |  87%Error in solve.default(oout$hessian) : 
  Lapack routine dgesv: system is exactly singular: U[4,4] = 0

  |                                                                            
  |================================================================      |  91%
  |                                                                            
  |===================================================================   |  96%
  |                                                                            
  |======================================================================| 100%</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in nlminb(start = start, objective = f, control = optim.control):
NA/NaN function evaluation</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in MLE(ll4, start = list(eta.mu = eta.mu, eta.sigma = eta.sigma, :
possible convergence problem: optim gave code=1 function evaluation limit
reached without convergence (9)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ahora mostramos los valores AIC </span></span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>contenedor<span class="sc">$</span>fits</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        GA         GG       BCCG      BCCGo     exGAUS        GIG       BCPE 
  41.64935   41.86595   41.93903   41.93903   42.47334   43.64935   43.87114 
     BCPEo        GB2        BCT       BCTo     LOGNO2      LOGNO         IG 
  43.87114   43.88685   43.93903   43.93903   46.26678   46.26678   46.34586 
    IGAMMA       WEI3        WEI       WEI2        EXP   PARETO2o    PARETO2 
  53.83497   80.09708   80.09708   80.09708 1644.00544 1646.00784 1646.00847 
        GP 
1646.00888 </code></pre>
</div>
</div>
<p>Ahora podemos observar mediante la lista que el menor valor AIC es el de GA osea Gamma, lo que quiere decir que la distribución gamma explica mejor los datos de la muestra aleatoria creada.</p>
<p>En adición, podemos calcular los parámetros α y λ de la muestra aleatoria creada y comparar con nuestros valores alfa y lambda de nuestra variable <strong>TIEMPO DE ESPERA</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>contenedor<span class="sc">$</span>mu</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.900288</code></pre>
</div>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>contenedor<span class="sc">$</span>sigma </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1330046</code></pre>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>alf<span class="ot">&lt;-</span><span class="fl">14.10638</span><span class="sc">*</span><span class="fl">14.10638</span><span class="sc">/</span> <span class="fl">105.9671</span> <span class="co">#alfa y lamda de la varible tiempo de espera</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>lamb<span class="ot">&lt;-</span><span class="fl">14.10638</span><span class="sc">/</span> <span class="fl">105.9671</span></span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a>alf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.877847</code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>lamb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1331204</code></pre>
</div>
</div>
<p>Podemos observar que alfa=1.900288 y lamba=0.133046 corresponden a nuestra muestra aleatoria, mientras que los valores alfa=1.877847 y lambda=0.1331204. En consecuencia la función <code>fitDists</code> logró identificar correctamente la distribución y los parámetros alfa y lambda respectivamente, con lo cual la variable <strong>TIEMPO DE ESPERA</strong> sigue una distribución gamma</p>
<p>Ahora después de obtener los valores de alfa y lambda y vemos que se cumple gráficamente podemos realizar un ejercicio</p>
<p>1. Cual es la probabilidad de que un estudiante de Utec espere más 20 min en la cafetería.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>alf<span class="ot">&lt;-</span><span class="fl">14.10638</span><span class="sc">*</span><span class="fl">14.10638</span><span class="sc">/</span> <span class="fl">105.9671</span> </span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>lamb<span class="ot">&lt;-</span><span class="fl">14.10638</span><span class="sc">/</span> <span class="fl">105.9671</span> </span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pgamma</span>(<span class="dv">20</span>, alf, lamb,<span class="at">lower.tail=</span><span class="cn">FALSE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2277175</code></pre>
</div>
</div>
<p>vemos que el porcentaje teórico es de 22.77%, mientras que el real es de 27.65%. El valor real es el número de casos favorables que tenemos en nuestra muestra entre el número de nuestro universo de los cuales consumen actualmente en la cafetería. En este caso nuestra muestra es de 94 personas, ya que estamos tomando el tiempo de espera de los que si consumen actualmente en nuestra cafetería</p>
<p>Nuestra aproximación es buena y no esta muy alejada del valor real.</p>
<p>Con esta gráfica podemos observar cual es la probabilidad de que un estudiante espere entre 0 a 20 min en la cafetería</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">dgamma</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">20</span>,alf,lamb ), <span class="at">type =</span> <span class="st">"h"</span>,<span class="at">col =</span> <span class="st">"68"</span>, <span class="at">lwd =</span> <span class="dv">2</span>,<span class="at">ylab =</span> <span class="st">"Probabilidad de que espere"</span>, <span class="at">xlab =</span> <span class="st">"Número de minutos"</span>)  </span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span> (<span class="at">v =</span> <span class="fu">mean</span> (DF<span class="sc">$</span>tiempo_espera,<span class="at">na.rm=</span>T), <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Podemos concluir que nuestra variable si cumple con el comportamiento de una distribución gamma, por otro lado observamos que la probabilidad de que un estudiante espera más minutos en la cafetería que la media va disminuyendo. Otro punto a recalcar es que si fuéramos a recolectar más encuestas observaríamos como nuestra variable tiempo de espera se va asemejando cada vez más a una distribución gamma.</p>
</section>
<section id="consumo-semanal-actualvariable-discreta" class="level3">
<h3 class="anchored" data-anchor-id="consumo-semanal-actualvariable-discreta">CONSUMO SEMANAL ACTUAL:variable discreta</h3>
<p><span class="math inline">\(X \sim BinNegativa(n,p)\)</span></p>
<p>Al ser una variable discreta podemos aproximar a cualquier modelo discreto. En esta caso lo aproximaremos al modelo <strong>BINOMIAL NEGATIVO,</strong></p>
<p><span class="math inline">\(X\)</span> cuenta el número de ensayos o intentos con <span class="math inline">\(Ber(p)\)</span> independientes que debe realizar hasta lograr <strong>n</strong> éxitos con n&gt;1.</p>
<p>Definimos nuestra Bernulli subyacente: en este caso a nuestro éxito lo definiremos como las personas que consuman 2 días en el comedor de Utec actualmente. Hallamos la probabilidad de éxito.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>X<span class="ot">&lt;-</span>DF<span class="sc">$</span>consumo_semanal_actual[DF<span class="sc">$</span>consumo_semanal_actual<span class="sc">==</span><span class="dv">2</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(DF<span class="sc">$</span>consumo_semanal_actual)]</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">table</span>(X))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32</code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">table</span>(DF<span class="sc">$</span>consumo_semanal_actual[<span class="sc">!</span><span class="fu">is.na</span>(DF<span class="sc">$</span>consumo_semanal_actual)]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 94</code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>P_exito<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">sum</span>(<span class="fu">table</span>(X))<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">table</span>(DF<span class="sc">$</span>consumo_semanal_actual[<span class="sc">!</span><span class="fu">is.na</span>(DF<span class="sc">$</span>consumo_semanal_actual)])),<span class="dv">2</span>)</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>P_exito</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.34</code></pre>
</div>
</div>
<p><span class="math inline">\(X\)</span> : # de personas que consumen actualmente en la cafetería, hasta obtener que n personas consuman 2 días en la cafetería según nuestro estudio realizado a los estudiantes de Utec.</p>
<p><span class="math display">\[\mathbb{x\sim BinBegativa(n,p)}=
\begin{cases}
n &amp; \text{número de exitos(de personas)} \\
p &amp; \text{probabilidad de éxitp definido como: personas que consumen 2 días en la cafetería}
\end{cases}
\]</span></p>
<p>Ahora construimos nuestra gráfica de densidad, este caso queremos que n= 5 (personas consuman dos días)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>numero_de_personas<span class="ot">&lt;-</span><span class="fu">sum</span>(<span class="fu">table</span>(DF<span class="sc">$</span>consumo_semanal_actual[<span class="sc">!</span><span class="fu">is.na</span>(DF<span class="sc">$</span>consumo_semanal_actual)]))</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>prob_exito <span class="ot">&lt;-</span><span class="fl">0.34</span></span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a>num_personas_max <span class="ot">&lt;-</span> numero_de_personas</span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una secuencia de valores para el número de personas</span></span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a>num_personas_seq <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span>num_personas_max</span>
<span id="cb133-7"><a href="#cb133-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-8"><a href="#cb133-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la probabilidad correspondiente a que haya 5 éxitos en cada número de personas</span></span>
<span id="cb133-9"><a href="#cb133-9" aria-hidden="true" tabindex="-1"></a>probabilidades <span class="ot">&lt;-</span> <span class="fu">dnbinom</span>(<span class="dv">5</span>, <span class="at">size =</span> num_personas_seq, <span class="at">prob =</span> prob_exito)</span>
<span id="cb133-10"><a href="#cb133-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-11"><a href="#cb133-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la densidad</span></span>
<span id="cb133-12"><a href="#cb133-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(num_personas_seq, probabilidades, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb133-13"><a href="#cb133-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Cantidad de personas"</span>, <span class="at">ylab =</span> <span class="st">"Probabilidad"</span>,</span>
<span id="cb133-14"><a href="#cb133-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Probabilidad de 5 éxitos en función de la cantidad de personas"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Podemos observar que la probabilidad de encontrar 5 personas que coman 2 días en la cafetería dada la cantidad de personas disminuye, esto se debe a que a medida que aumenta el tamaño de la muestra, hay más variabilidad y más posibilidades de que los éxitos se distribuyan de diferentes maneras entre las personas. Por lo tanto, la probabilidad de obtener un número específico de éxitos en una muestra más grande será menor. En consecuencia a medida que aumenta el tamaño de la muestra, la probabilidad de obtener exactamente 5 éxitos disminuye porque hay más posibilidades para los resultados posibles. También es importante tener en cuenta que la forma y la magnitud exacta de la disminución de la probabilidad dependerán de los parámetros específicos de la distribución binomial negativa, como la probabilidad de éxito y el tamaño de la muestra.</p>
<p>Ahora calculamos el valor esperado y la varianza, según nuestro modelo binomial negativo: ¿Cuántas personas en promedio tenemos que encuestar para que 5 de ellas almuercen exactamente 2 días a la semana.</p>
<p>SOLUCION:</p>
<p><span class="math inline">\(Ber(p)\)</span> = P_EXITO –&gt; 0.34</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Bernulli subyacente Ber(p)</span></span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>P_exito <span class="co"># igual a 0.34, hallado en la primera parte </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.34</code></pre>
</div>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="math inline">\(Y \sim BinNegativa(n,p)\space donde\ n=5\ y\ p=0.34\)</span></p>
<p><span class="math inline">\(Y\)</span> cuenta el número de encuestas o intentos hasta obtener la quinta persona que almuerza 2 días a la semana</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>EX<span class="ot">&lt;-</span><span class="dv">5</span><span class="sc">/</span><span class="fl">0.34</span></span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>varianza<span class="ot">&lt;-</span>n<span class="sc">*</span>(<span class="dv">1</span><span class="fl">-0.34</span>)<span class="sc">/</span><span class="fl">0.34</span><span class="sc">^</span><span class="dv">2</span></span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a>EX</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.70588</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a>varianza</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28.54671</code></pre>
</div>
</div>
<p>En conclusión tenemos que encuestar a 15 personas para poder para obtener 5 personas que almuerzan 2 días a la semana.</p>
<p>Por otro lado la varianza con valores altos indica una mayor dispersión de los valores alrededor de la media (EX), lo que significa que los números de ensayos necesarios para obtener el número deseado de éxitos pueden variar más ampliamente.</p>
<p>El código proporcionado utiliza las funciones <strong><code>ecdf()</code></strong> y <strong><code>plot()</code></strong> para graficar las funciones de distribución acumulativa empírica (ECDF) de dos conjuntos de datos diferentes: <code>consumo semanal actual</code> y <code>consumo semanal previo</code>. La ECDF es una función que muestra la proporción acumulada de observaciones que son menores o iguales a un determinado valor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>F <span class="ot">&lt;-</span> <span class="fu">ecdf</span>(DF<span class="sc">$</span>consumo_semanal_actual)</span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(F, <span class="at">las=</span><span class="dv">1</span>, <span class="at">main=</span><span class="st">''</span>) </span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>F2 <span class="ot">&lt;-</span><span class="fu">ecdf</span>((DF<span class="sc">$</span>consumo_semanal_previo)) </span>
<span id="cb141-4"><a href="#cb141-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(F2, <span class="at">col=</span><span class="st">'red'</span>, <span class="at">add=</span>T) </span>
<span id="cb141-5"><a href="#cb141-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">'bottomright'</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">'consumo semanal actual'</span>, <span class="st">'Consumo semanal previo'</span>),        <span class="at">col=</span><span class="fu">c</span>(<span class="st">'black'</span>, <span class="st">'red'</span>), <span class="at">lwd=</span><span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>consumo semanal actual: se encuentra por encima de la línea roja (representando el consumo semanal previo) en un punto dado en el gráfico, eso indica que la proporción acumulada de personas con un consumo semanal actual menor o igual a ese punto es mayor que la proporción acumulada de personas con un consumo semanal previo menor o igual a ese punto.</li>
</ul>
</section>
<section id="presupuesto-variable-continua" class="level3">
<h3 class="anchored" data-anchor-id="presupuesto-variable-continua">Presupuesto: Variable continua</h3>
<p>Primero graficamos el histograma y su curva de densidad</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a>q<span class="ot">&lt;-</span>DF<span class="sc">$</span>presupuesto[<span class="sc">!</span><span class="fu">is.na</span>(DF<span class="sc">$</span>presupuesto)]</span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(DF<span class="sc">$</span>presupuesto, <span class="at">breaks =</span> <span class="dv">22</span>, <span class="at">freq =</span> <span class="cn">FALSE</span>, <span class="at">main =</span> <span class="st">"Histograma de la variable presupuesto"</span>, <span class="at">xlab =</span> <span class="st">"soles"</span>, <span class="at">col =</span> <span class="st">"darkorange3"</span>)  </span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(DF<span class="sc">$</span>presupuesto, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se separan los datos de la variable presupuesto y se asignan a un vector todos los valores menos los NA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fitdistrplus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'fitdistrplus' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> DF<span class="sc">$</span>presupuesto[<span class="sc">!</span><span class="fu">is.na</span>(DF<span class="sc">$</span>presupuesto)]</span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a>fw<span class="ot">&lt;-</span><span class="fu">fitdist</span>(q,<span class="st">'weibull'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Con este método puedo saber a que distribución se asemeja mas a mi variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>fga<span class="ot">&lt;-</span><span class="fu">fitdist</span>(q,<span class="st">'gamma'</span>)</span>
<span id="cb147-2"><a href="#cb147-2" aria-hidden="true" tabindex="-1"></a>fln<span class="ot">&lt;-</span><span class="fu">fitdist</span>(q,<span class="st">'lnorm'</span>)</span>
<span id="cb147-3"><a href="#cb147-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb147-4"><a href="#cb147-4" aria-hidden="true" tabindex="-1"></a>plot.legend<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">'weibull'</span>,<span class="st">'lognormal'</span>,<span class="st">'gamma'</span>)</span>
<span id="cb147-5"><a href="#cb147-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-6"><a href="#cb147-6" aria-hidden="true" tabindex="-1"></a><span class="fu">denscomp</span>(<span class="fu">list</span>(fw,fln,fga),<span class="at">legendtext=</span>plot.legend)</span>
<span id="cb147-7"><a href="#cb147-7" aria-hidden="true" tabindex="-1"></a><span class="fu">qqcomp</span>(<span class="fu">list</span>(fw,fln,fga),<span class="at">legendtext=</span>plot.legend)</span>
<span id="cb147-8"><a href="#cb147-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ppcomp</span>(<span class="fu">list</span>(fw,fln,fga),<span class="at">legendtext=</span>plot.legend)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica que se obtiene utilizando la biblioteca <strong><code>fitdistrplus</code></strong> y los diferentes métodos de ajuste de distribución (Weibull, Lognormal y Gamma)</p>
<ol type="1">
<li><p>Gráfica de densidad comparativa (<strong><code>denscomp</code></strong>): Esta gráfica muestra la comparación de las densidades ajustadas para las tres distribuciones (Weibull, Lognormal y Gamma) en función del rango de los datos observados. se puede observar cómo se ajusta cada distribución a los datos y comparar la forma y ubicación de las curvas de densidad.</p></li>
<li><p>Gráfica QQ comparativa (<strong><code>qqcomp</code></strong>): Esta gráfica compara los cuantiles teóricos de cada distribución con los cuantiles observados de nuestros datos. Si las distribuciones se ajustan bien a los datos , los puntos deberían caer aproximadamente en una línea diagonal o mejor dicho es lineal. Con estos gráficos podemos decidir que distribución se asemeja mejor a nuestros datos de la variable presupuesto.</p></li>
<li><p>Gráfica de probabilidad inversa comparativa (<strong><code>ppcomp</code></strong>): Esta gráfica compara las probabilidades inversas ajustadas para cada distribución. Muestra cómo se ajustan las probabilidades inversas teóricas con las probabilidades inversas observadas en nuestros datos, en donde la mejor distribución se asemeja mas a una función lineal.</p></li>
</ol>
<p>Por lo tanto podemos decir mediante las gráficas que la distribución de nuestros datos se parece más a la distribución lognormal y con la función summary obtenemos los parámetros meanlog y sdlog respectivamente</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fln)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fitting of the distribution ' lnorm ' by maximum likelihood 
Parameters : 
         estimate Std. Error
meanlog 3.7781945 0.08855108
sdlog   0.8585346 0.06261469
Loglikelihood:  -474.1928   AIC:  952.3857   BIC:  957.4723 
Correlation matrix:
        meanlog sdlog
meanlog       1     0
sdlog         0     1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a>meanlog1<span class="ot">&lt;-</span><span class="fl">3.7781945</span></span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a>sdlog1<span class="ot">&lt;-</span><span class="fl">0.8585346</span></span>
<span id="cb150-3"><a href="#cb150-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(DF<span class="sc">$</span>presupuesto, <span class="at">breaks =</span> <span class="dv">22</span>, <span class="at">freq =</span> <span class="cn">FALSE</span>, <span class="at">main =</span> <span class="st">"Histograma de la variable presupuesto"</span>, <span class="at">xlab =</span> <span class="st">"soles"</span>, <span class="at">col =</span> <span class="st">"darkorange3"</span>)  </span>
<span id="cb150-4"><a href="#cb150-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(DF<span class="sc">$</span>presupuesto, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>) </span>
<span id="cb150-5"><a href="#cb150-5" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dlnorm</span>(x,meanlog1,sdlog1),<span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">add =</span> T) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ahora podemos realizar un ejercicio :</p>
<p>Calcular la probabilidad de que un estudiante tenga más de 100 soles de presupuesto para gastar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a>valor_expe<span class="ot">&lt;-</span><span class="fu">plnorm</span>(<span class="dv">100</span>,meanlog1,sdlog1,<span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a>valor_expe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1677133</code></pre>
</div>
</div>
<p>como podemos verificar si es cierto:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>numerador<span class="ot">&lt;-</span><span class="fu">sum</span>(<span class="fu">table</span>(DF<span class="sc">$</span>presupuesto[DF<span class="sc">$</span>presupuesto<span class="sc">&gt;</span><span class="dv">100</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(DF<span class="sc">$</span>presupuesto)]))</span>
<span id="cb153-2"><a href="#cb153-2" aria-hidden="true" tabindex="-1"></a>denominador<span class="ot">&lt;-</span><span class="fu">sum</span>(<span class="fu">table</span>(DF<span class="sc">$</span>presupuesto[<span class="sc">!</span><span class="fu">is.na</span>(DF<span class="sc">$</span>presupuesto)]))</span>
<span id="cb153-3"><a href="#cb153-3" aria-hidden="true" tabindex="-1"></a><span class="co">#probabilidad empirica de que gaste mas de 100 soles es\</span></span>
<span id="cb153-4"><a href="#cb153-4" aria-hidden="true" tabindex="-1"></a>valor_teorico<span class="ot">&lt;-</span>numerador<span class="sc">/</span>denominador</span>
<span id="cb153-5"><a href="#cb153-5" aria-hidden="true" tabindex="-1"></a>valor_teorico</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1170213</code></pre>
</div>
</div>
<p>Podemos observar que la diferencia no es muy grande, ademas de que si encuestáramos mas personas nuestra muestra crecería por ende los valores teóricos que podríamos obtener se acercarían a nuestro valor experimental con la distribución lognormal.</p>
</section>
<section id="variable-discreta-menú-previo" class="level3">
<h3 class="anchored" data-anchor-id="variable-discreta-menú-previo">Variable discreta: Menú previo</h3>
<p><span class="math display">\[
\mathbb{X} \sim Bin(n,p)
\]</span></p>
<p>Realizamos un experimento aleatorio, donde analizamos la probabilidad de encontrar 1 persona que consumía principalmente el plato a la carta en la cafetería de la concesionaria anterior al escoger a 10 personas aleatoriamente del conjunto de consumidores de la concesionaria anterior, si es que todos tienen la misma probabilidad de ser elegidos, y pueden aparecer múltiples veces en el mismo intento.</p>
<p>Para este experimento usaremos una distribución binomial, pues realizamos <code>n</code> intentos con probabilidad p, y consideramos que cada intento se realiza con reemplazo, por lo que se puede operar en R sin problemas.</p>
<p>Hallamos la probabilidad de hallar una persona que consumía plato a la carta de las personas que consumían anteriormente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a>pplato <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(menu_previo<span class="sc">==</span><span class="st">"Plato a la Carta"</span>))</span>
<span id="cb155-2"><a href="#cb155-2" aria-hidden="true" tabindex="-1"></a>previototal <span class="ot">&lt;-</span> <span class="fu">nrow</span>(DF <span class="sc">%&gt;%</span> <span class="fu">filter</span>(consumio_previo<span class="sc">==</span><span class="st">"Si"</span>))</span>
<span id="cb155-3"><a href="#cb155-3" aria-hidden="true" tabindex="-1"></a>pplato<span class="sc">/</span>previototal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1165049</code></pre>
</div>
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a>pplato</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a>previototal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 103</code></pre>
</div>
</div>
<p>Nuestra probabilidad de éxito <code>p</code> es igual a <code>12/103</code> = <code>0.1165049</code></p>
<p>Nuestro número de intentos <code>n</code> es igual a 10, como definimos en el experimento.</p>
<p>Así es como nuestra variable aleatoria discreta resulta:</p>
<p><span class="math display">\[
\mathbb{X} \sim Bin(10, \frac{12}{103})
\]</span>Ahora calculamos el valor esperado y la varianza:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a>Ex <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="sc">*</span> pplato<span class="sc">/</span>previototal</span>
<span id="cb161-2"><a href="#cb161-2" aria-hidden="true" tabindex="-1"></a>Vx <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="sc">*</span> pplato<span class="sc">/</span>previototal <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> pplato<span class="sc">/</span>previototal)</span>
<span id="cb161-3"><a href="#cb161-3" aria-hidden="true" tabindex="-1"></a>Ex</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.165049</code></pre>
</div>
<div class="sourceCode cell-code" id="cb163"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb163-1"><a href="#cb163-1" aria-hidden="true" tabindex="-1"></a>Vx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.029315</code></pre>
</div>
</div>
<p>Esto significa que la mayoría de veces se espera encontrar 1 comensal que consumía principalmente el plato a la carta entre los 10 seleccionados.</p>
<p>Visualizamos la gráfica de probabilidad acumulada de la variable menú previo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a>cdf <span class="ot">&lt;-</span> <span class="fu">pbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">prob =</span> pplato<span class="sc">/</span>previototal)</span>
<span id="cb165-2"><a href="#cb165-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-3"><a href="#cb165-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">10</span>, cdf, <span class="at">type =</span> <span class="st">"s"</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb165-4"><a href="#cb165-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Número de aciertos"</span>, <span class="at">ylab =</span> <span class="st">"Probabilidad Acumulada"</span>,</span>
<span id="cb165-5"><a href="#cb165-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Menú Previo - Función de probabilidad Acumulada"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Observamos que el mayor salto se encuentra entre 0 aciertos y 1 acierto, lo cual es de esperar dado que el valor esperado es cercano a 1 acierto. Igualmente cabe notar que la gráfica tiene el suelo en 0.3, que es la probabilidad de no encontrar a ninguna persona que consuma principalmente el plato a la carta en los 10 seleccionados.</p>
<p>A continuación, simulamos el experimento 1000 veces, y visualizamos en un histograma los resultados de la variable menú previo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1000</span>, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">prob =</span> pplato<span class="sc">/</span>previototal)</span>
<span id="cb166-2"><a href="#cb166-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb166-3"><a href="#cb166-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(samples, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.5</span>, n <span class="sc">+</span> <span class="fl">0.5</span>), <span class="at">col =</span> <span class="st">"yellow"</span>,</span>
<span id="cb166-4"><a href="#cb166-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Número de aciertos"</span>, <span class="at">ylab =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb166-5"><a href="#cb166-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Menú Previo - Histograma del experimento hecho 1000 veces"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="S7_Informe_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Podemos concluir así, que si hubiésemos entrevistado a 10 personas aleatoriamente en la cafetería de la concesionaria del ciclo 2022-2, hubiéramos encontrado la mayoría de veces 1 persona que consumía principalmente el plato a la carta. sí afirmamos que un estimado muy crudo nos dice que al rededor del 10% de los consumidores compraban principalmente este producto, el cual no está disponible a la venta en la nueva concesionaria (no consideramos a aquellos que lo consumían ocasionalmente).</p>
</section>
<section id="conclusiones-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusiones-1">Conclusiones:</h3>
<p>Mediante el análisis estadístico pudimos conocer la cantidad de alumnos los cuales consumen y no consumen en el concesionario actual .</p>
<p>También tomamos registro de la opinión sobre la calidad del servicio brindado, en donde encontramos que la mayoría de alumnos los cuales consumen actualmente pertenecían a ciclo entre 4to a 7mo ciclo, entre las razones son los “Precios Elevados”. Al momento de comparar la opinión con la concesionaria anterior encontramos la misma opinión sobre los Precios.</p>
<p>Mediante el análisis probabilístico pudimos generar un espacio muestral mediante nuestros datos recolectados y saber cual es la probabilidad de que los alumnos consuman en la concesionaria actual.</p>
<p>También le dimos modelos a nuestros posible eventos para poder analizar el comportamiento de los consumidores y del servicio de la cafetería.Los consumidores esperarían alrededor de 8 a 10 minutos, lo cual es un tiempo ideal teniendo en cuenta que la mayoría de alumnos disponen de alrededor de 40 minutos para almorzar.</p>
<p>Sobre la preferencia de los consumidores de la concesionaria anterior encontramos que también la mayoría optaba por el estudiantil.</p>
<p>Con la información previa, concluimos que actualmente la mayoría de los alumnos no hacen uso del concesionario.Podemos recomendar hacer un ajuste sobre los precios de los menús. Para que mas alumnos puedan acceder o optar por este. Finalmente también recomendamos que se tenga una mayor atención a la calidad sobre el “Menú estudiantil”, debido a que es el mas solicitado,tanto actualmente como en la concesionaria&nbsp;anterior.<br>
</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>