---
title: "LipiezaDeDatos"
author: "Santi"
date: "`r Sys.Date()`"
output: html_document
---

librerias
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(crayon)
library(DescTools)
```

carga de datos
```{r}
DF <- read_csv("Encuesta.csv")
```
eliminamos una columna irrelevante
```{r}
DF <- subset(DF, select = -`Marca temporal`)
```


Cambiamos nombres de las variables

```{r}
names(DF)[1]<-"Genero"
names(DF)[2]<-"Edad"
names(DF)[3]<-"Carrera"
names(DF)[4]<-"Ciclo_actual"
names(DF)[5]<-"Promedio_primer_ciclo"
names(DF)[6]<-"Creditos_ciclo_pasado"
names(DF)[7]<-"Promedio_ciclo_pasado"
names(DF)[8]<-"Numero_de_cursos"
names(DF)[9]<-"Rendimiento_academico"
names(DF)[10]<-"Considera_predominancia_masculino"
names(DF)[11]<-"Considera_predominancia_femenino"
names(DF)[12]<-"Factores_eleccion_de_carrera"
names(DF)[13]<-"considero_cambiar_de_carrera"
names(DF)[14]<-"carrera_considero_cambiarse"
names(DF)[15]<-"considero_retirarse_universdad"
names(DF)[16]<-"razones_considero_retirarse_universdad"
```

modificamos el tipo de variables

```{r}
DF$Promedio_primer_ciclo<- as.numeric(DF$Promedio_primer_ciclo)
DF$Promedio_ciclo_pasado<- as.numeric(DF$Promedio_ciclo_pasado)
```


pedimos un resumen de los datos

```{r}
summary(DF)
```

limpiamos datos que no nos sirven 

```{r}
DF<-subset(DF, Ciclo_actual != 1) #LOS QUE ESTAN EN CICLO 1 NO SON OBJETOS QUE CONTRIBUYAN AL ESTUDIO
```


```{r}
DF<-subset(DF, Edad != 12)
DF<-subset(DF, Edad != 188)
 	
DF<-subset(DF, Genero != "Prefiero no decirlo")# NO ES OBJETO DE ESTUDIO O NO ES POSIBLE 
```
```{r}
DF$Considera_predominancia_femenino <- gsub("computación", "Computación", DF$Considera_predominancia_femenino)

```

llenamos N.A.
```{r}
DF[DF$considero_cambiar_de_carrera == "2. No", "carrera_considero_cambiarse"] <- "No lo he considerado"
DF[DF$considero_retirarse_universdad == "2. No", "razones_considero_retirarse_universdad"] <- "7. No lo he considerado"

```

```{r}
DF <- na.omit(DF)

```


```{r}
write.csv(DF, "C:/Users/Santiago Perez/ESTADISTICAS/Poryecto/BaseDeDatosLimpia.csv", row.names = FALSE)

```


