# LIBRERIAS

library(readr)
library(plyr)
library(dplyr)
library(tidyverse)
library(stringr)
library(foreign)
library(haven)

# ARCHIVOS DEL ENEDIS: 
CaracteristicasdelasPersonasconDiscapacidad <- read_sav("CaracteristicasdelasPersonasconDiscapacidad.sav")
CAP_700_EMPLEO <- read_sav("CAP_700_EMPLEO.sav")
CAP_500_EDUCACION <- read_sav("CAP_500_EDUCACION.sav")
CAP_600_SALUD <- read_sav("CAP_600_SALUD.sav")
write.csv(CaracteristicasdelasPersonasconDiscapacidad, "CaracteristicasdelasPersonasconDiscapacidad.csv")
write.csv(CAP_700_EMPLEO, "CAP_700_EMPLEO.csv")
write.csv(CAP_500_EDUCACION, "CAP_500_EDUCACION.csv")
write.csv(CAP_600_SALUD, "CAP_600_SALUD.csv")

# FILTRACION DE LA BASE DE DATOS DEL ENEDIS:

## CARACTERISTICAS GENERALES DE LAS PERSONAS DISCAPACITADAS: 
P_DISC <- read_csv("CaracteristicasdelasPersonasconDiscapacidad.csv")
TUM_DISC <- filter(P_DISC, P_DISC$NOMBREDD == "TUMBES")
TUM_DISC <- TUM_DISC[,-1:-10]
TUM_DISC <- TUM_DISC[,-3: -5]
TUM_DISC <- TUM_DISC[,-4:-9]
TUM_DISC <- rename(TUM_DISC, Sexo = P105, Edad = P106, Nivel_Educativo = P109_1)
TUM_DISC$Sexo[TUM_DISC$Sexo == 1] <- 'H'
TUM_DISC$Sexo[TUM_DISC$Sexo == 2] <- 'M'
TUM_DISC$Nivel_Educativo[TUM_DISC$Nivel_Educativo == 1] <- "Sin nivel"
TUM_DISC$Nivel_Educativo[TUM_DISC$Nivel_Educativo == 2] <- "Educación inicial"
TUM_DISC$Nivel_Educativo[TUM_DISC$Nivel_Educativo == 3] <- "Educación primaria"
TUM_DISC$Nivel_Educativo[TUM_DISC$Nivel_Educativo == 4] <- "Educación secundaria"
TUM_DISC$Nivel_Educativo[TUM_DISC$Nivel_Educativo == 5] <- "Educación básica especial"
TUM_DISC$Nivel_Educativo[TUM_DISC$Nivel_Educativo == 6] <- "Superior no universitaria"
TUM_DISC$Nivel_Educativo[TUM_DISC$Nivel_Educativo == 7] <- "Superior universitaria"
TUM_DISC$Nivel_Educativo[TUM_DISC$Nivel_Educativo == 8] <- "Maestría / doctorado"
TUM_DISC$Nivel_Educativo[TUM_DISC$Nivel_Educativo == 9] <- "Sin respuesta"


## SALUD:
HP_DISC <- read_csv("CAP_600_SALUD.csv")
HTUM_DISC <- filter(HP_DISC,P_DISC$NOMBREDD == "TUMBES" )
HTUM_DISC <- select(HTUM_DISC, P621_1)
HTUM_DISC <- rename(HTUM_DISC, Numero_de_hijos = P621_1)


## EMPLEO EN LAS PERSONAS CON DISCAPACIDAD:
SP_DISC <- read_csv("CAP_700_EMPLEO.csv")
STUM_DISC <- filter(SP_DISC, SP_DISC$NOMBREDD == "TUMBES")
STUM_DISC <- STUM_DISC[,-1:-22]
STUM_DISC <- STUM_DISC[,-13:-14]
STUM_DISC <- STUM_DISC[,-14:-36]
STUM_DISC <- STUM_DISC[,-17:-40]
STUM_DISC <- STUM_DISC[,-18:-54]
STUM_DISC <- STUM_DISC[,-19:-60]
STUM_DISC <- STUM_DISC[,-20:-112]

STUM_DISC <- rename(STUM_DISC, 
              NEGOCIO_PROPIO_O_DE_UN_FAMILIAR = 'P704$01'     ,                    OFRECIENDO_ALGÚN_SERVICIO = 'P704$02' , 
                         COMERCIO_AMBULATORIO = 'P704$03'     ,            HACIENDO_ALGO_EN_CASA_PARA_VENDER = 'P704$04' , 
                          VENDIENDO_PRODUCTOS = 'P704$05'     ,                              LABOR_ARTESANAL = 'P704$06' , 
                   HACIENDO_PRACTICAS_PAGADAS = 'P704$07'     ,          TRABAJANDO_PARA_UN_HOGAR_PARTICULAR = 'P704$08' , 
                    FABRICANDO_ALGÚN_PRODUCTO = 'P704$09'     ,             LABORES_REMUNERADAS_EN_AL_CHACRA = 'P704$10' ,
                       AYUDANDO_A_UN_FAMILIAR = 'P704$11'     ,                        PROGRAMA_TRABAJA_PERÚ = 'P704$12' ,  
                                    OCUPACIÓN = P705_1        ,                   CUANTAS_PERSONAS_LABORARON = P711      ,
  CUANTAS_PERSONAS_CON_DISCAPACIDAD_LABORARON = P712          ,                    HORAS_TRABAJÓ_A_LA_SEMANA = P713      , 
                            INGRESO_PRINCIPAL = P722_1        ,                           INGRESO_SECUNDARIO = P725      , 
       CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO = P745)

STUM_DISC$NEGOCIO_PROPIO_O_DE_UN_FAMILIAR[STUM_DISC$NEGOCIO_PROPIO_O_DE_UN_FAMILIAR == 1] <- "Si"
STUM_DISC$NEGOCIO_PROPIO_O_DE_UN_FAMILIAR[STUM_DISC$NEGOCIO_PROPIO_O_DE_UN_FAMILIAR == 2] <- "No"
STUM_DISC$OFRECIENDO_ALGÚN_SERVICIO[STUM_DISC$OFRECIENDO_ALGÚN_SERVICIO == 1] <- "Si"
STUM_DISC$OFRECIENDO_ALGÚN_SERVICIO[STUM_DISC$OFRECIENDO_ALGÚN_SERVICIO == 2] <- "No"
STUM_DISC$COMERCIO_AMBULATORIO[STUM_DISC$COMERCIO_AMBULATORIO == 1] <- "Si"
STUM_DISC$COMERCIO_AMBULATORIO[STUM_DISC$COMERCIO_AMBULATORIO == 2] <- "No"
STUM_DISC$HACIENDO_ALGO_EN_CASA_PARA_VENDER[STUM_DISC$HACIENDO_ALGO_EN_CASA_PARA_VENDER == 1] <- "Si"
STUM_DISC$HACIENDO_ALGO_EN_CASA_PARA_VENDER[STUM_DISC$HACIENDO_ALGO_EN_CASA_PARA_VENDER == 2] <- "No"
STUM_DISC$VENDIENDO_PRODUCTOS[STUM_DISC$VENDIENDO_PRODUCTOS == 1] <- "Si"
STUM_DISC$VENDIENDO_PRODUCTOS[STUM_DISC$VENDIENDO_PRODUCTOS == 2] <- "No"
STUM_DISC$LABOR_ARTESANAL[STUM_DISC$LABOR_ARTESANAL == 1] <- "Si"
STUM_DISC$LABOR_ARTESANAL[STUM_DISC$LABOR_ARTESANAL == 2] <- "No"
STUM_DISC$HACIENDO_PRACTICAS_PAGADAS[STUM_DISC$HACIENDO_PRACTICAS_PAGADAS == 1] <- "Si"
STUM_DISC$HACIENDO_PRACTICAS_PAGADAS[STUM_DISC$HACIENDO_PRACTICAS_PAGADAS == 2] <- "No"
STUM_DISC$TRABAJANDO_PARA_UN_HOGAR_PARTICULAR[STUM_DISC$TRABAJANDO_PARA_UN_HOGAR_PARTICULAR == 1] <- "Si"
STUM_DISC$TRABAJANDO_PARA_UN_HOGAR_PARTICULAR[STUM_DISC$TRABAJANDO_PARA_UN_HOGAR_PARTICULAR == 2] <- "No"
STUM_DISC$FABRICANDO_ALGÚN_PRODUCTO[STUM_DISC$FABRICANDO_ALGÚN_PRODUCTO == 1] <- "Si"
STUM_DISC$FABRICANDO_ALGÚN_PRODUCTO[STUM_DISC$FABRICANDO_ALGÚN_PRODUCTO == 2] <- "No"
STUM_DISC$LABORES_REMUNERADAS_EN_AL_CHACRA[STUM_DISC$LABORES_REMUNERADAS_EN_AL_CHACRA == 1] <- "Si"
STUM_DISC$LABORES_REMUNERADAS_EN_AL_CHACRA[STUM_DISC$LABORES_REMUNERADAS_EN_AL_CHACRA == 2] <- "No"
STUM_DISC$AYUDANDO_A_UN_FAMILIAR[STUM_DISC$AYUDANDO_A_UN_FAMILIAR == 1] <- "Si"
STUM_DISC$AYUDANDO_A_UN_FAMILIAR[STUM_DISC$AYUDANDO_A_UN_FAMILIAR == 2] <- "No"
STUM_DISC$PROGRAMA_TRABAJA_PERÚ[STUM_DISC$PROGRAMA_TRABAJA_PERÚ == 1] <- "Si"
STUM_DISC$PROGRAMA_TRABAJA_PERÚ[STUM_DISC$PROGRAMA_TRABAJA_PERÚ == 2] <- "No"
STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO[STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO == 1] <- "No cambió"
STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO[STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO == 2] <- "Fue despedido"
STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO[STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO == 3] <- "Renunció"
STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO[STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO == 4] <- "Fue reubicado en un área adecuada"
STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO[STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO == 5] <- "Fue reubicado en un área inadecuada"
STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO[STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO == 6] <- "Recibió trato hostil"
STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO[STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO == 7] <- "Otro"
STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO[STUM_DISC$CÓMO_CAMBIÓ_SU_SITUACIÓN_EN_EL_TRABAJO == 9] <- "Sin respuesta"


STUM_DISC <- mutate_at(STUM_DISC, c("INGRESO_PRINCIPAL", "INGRESO_SECUNDARIO"), ~replace(., is.na(.), 0))
STUM_DISC %>% mutate(INGRESO_TOTAL = INGRESO_PRINCIPAL + INGRESO_SECUNDARIO) -> STUM_DISC
STUM_DISC$INGRESO_PRINCIPAL[STUM_DISC$INGRESO_PRINCIPAL == 0] <- NA
STUM_DISC$INGRESO_SECUNDARIO[STUM_DISC$INGRESO_SECUNDARIO == 0] <- NA
STUM_DISC$INGRESO_TOTAL[STUM_DISC$INGRESO_TOTAL == 0] <- NA


## EDUCACIÓN EN LAS PERSONAS CON DISCAPACIDAD:
EP_DISC <- read_csv("CAP_500_EDUCACION.csv")
ETUM_DISC <- filter(EP_DISC, EP_DISC$NOMBREDD == "TUMBES")
ETUM_DISC <- select(ETUM_DISC, 9:17, 21:21, P502, 46:47,50:52, P509, 72:75)
ETUM_DISC <- rename(ETUM_DISC, 
                         SEXO = P105        ,                         EDAD = P106        , SERVICIOS_HIGIENICOS_DISCAPACITADOS = 'P513_V1$4' ,
  LIMITACIÓN_PARA_MOVILIZARSE = P203        ,            LIMITACIÓN_VISUAL = P204        ,             LIMITACIÓN_COMUNICATIVA = P205        , 
          LIMITACIÓN_AUDITIVA = P206        ,       LIMITACIÓN_COMPRENSIVA = P207        ,        LIMITACIÓN_PARA_RELACIONARSE = P208        , 
    PADECE_ENFERMEDAD_CRÓNICA = P209        ,         SABE_LEER_Y_ESCRIBIR = P501        ,             ASISTE_CENTRO_EDUCATIVO = P502        , 
    PROFESORES_ESPECIALIZADOS = 'P508$1'    ,  COMPUTADORAS_ESPECIALIZADAS = 'P508$2'    ,                       LIBROS_BRAILE = 'P508$5'    , 
              LIBROS_HABLADOS = 'P508$6'    ,               LENGUAJE_SEÑAS = 'P508$7'    ,      NO_ASISTE_CENTRO_EDUCATIVO_POR = P509        , 
                RAMPAS_ACCESO = 'P513_V1$1' ,           BARANDAS_SEGURIDAD = 'P513_V1$2' ,                ASCENSORES_ADECUADOS = 'P513_V1$3' ,
)
ETUM_DISC$SERVICIOS_HIGIENICOS_DISCAPACITADOS[ETUM_DISC$SERVICIOS_HIGIENICOS_DISCAPACITADOS == 1] <- "Si"
ETUM_DISC$SERVICIOS_HIGIENICOS_DISCAPACITADOS[ETUM_DISC$SERVICIOS_HIGIENICOS_DISCAPACITADOS == 2] <- "No"
ETUM_DISC$SERVICIOS_HIGIENICOS_DISCAPACITADOS[ETUM_DISC$SERVICIOS_HIGIENICOS_DISCAPACITADOS == 3] <- "Sin respuesta"
ETUM_DISC$RAMPAS_ACCESO[ETUM_DISC$RAMPAS_ACCESO == 1] <- "Si"
ETUM_DISC$RAMPAS_ACCESO[ETUM_DISC$RAMPAS_ACCESO == 2] <- "No"
ETUM_DISC$RAMPAS_ACCESO[ETUM_DISC$RAMPAS_ACCESO == 3] <- "Sin respuesta"
ETUM_DISC$BARANDAS_SEGURIDAD[ETUM_DISC$BARANDAS_SEGURIDAD == 1] <- "Si"
ETUM_DISC$BARANDAS_SEGURIDAD[ETUM_DISC$BARANDAS_SEGURIDAD == 2] <- "No"
ETUM_DISC$BARANDAS_SEGURIDAD[ETUM_DISC$BARANDAS_SEGURIDAD == 3] <- "Sin respuesta"
ETUM_DISC$ASCENSORES_ADECUADOS[ETUM_DISC$ASCENSORES_ADECUADOS == 1] <- "Si"
ETUM_DISC$ASCENSORES_ADECUADOS[ETUM_DISC$ASCENSORES_ADECUADOS == 2] <- "No"
ETUM_DISC$ASCENSORES_ADECUADOS[ETUM_DISC$ASCENSORES_ADECUADOS == 3] <- "Sin respuesta"
ETUM_DISC$PROFESORES_ESPECIALIZADOS[ETUM_DISC$PROFESORES_ESPECIALIZADOS == 1] <- "Si"
ETUM_DISC$PROFESORES_ESPECIALIZADOS[ETUM_DISC$PROFESORES_ESPECIALIZADOS == 2] <- "No"
ETUM_DISC$PROFESORES_ESPECIALIZADOS[ETUM_DISC$PROFESORES_ESPECIALIZADOS == 3] <- "No sabe"
ETUM_DISC$COMPUTADORAS_ESPECIALIZADAS[ETUM_DISC$COMPUTADORAS_ESPECIALIZADAS == 1] <- "Si"
ETUM_DISC$COMPUTADORAS_ESPECIALIZADAS[ETUM_DISC$COMPUTADORAS_ESPECIALIZADAS == 2] <- "No"
ETUM_DISC$COMPUTADORAS_ESPECIALIZADAS[ETUM_DISC$COMPUTADORAS_ESPECIALIZADAS == 3] <- "No sabe"
ETUM_DISC$LIBROS_BRAILE[ETUM_DISC$LIBROS_BRAILE == 1] <- "Si"
ETUM_DISC$LIBROS_BRAILE[ETUM_DISC$LIBROS_BRAILE == 2] <- "No"
ETUM_DISC$LIBROS_BRAILE[ETUM_DISC$LIBROS_BRAILE == 3] <- "No sabe"
ETUM_DISC$LIBROS_HABLADOS[ETUM_DISC$LIBROS_HABLADOS == 1] <- "Si"
ETUM_DISC$LIBROS_HABLADOS[ETUM_DISC$LIBROS_HABLADOS == 2] <- "No"
ETUM_DISC$LIBROS_HABLADOS[ETUM_DISC$LIBROS_HABLADOS == 3] <- "No sabe"
ETUM_DISC$LENGUAJE_SEÑAS[ETUM_DISC$LENGUAJE_SEÑAS == 1] <- "Si"
ETUM_DISC$LENGUAJE_SEÑAS[ETUM_DISC$LENGUAJE_SEÑAS == 2] <- "No"
ETUM_DISC$LENGUAJE_SEÑAS[ETUM_DISC$LENGUAJE_SEÑAS == 3] <- "No sabe"
ETUM_DISC$ASISTE_CENTRO_EDUCATIVO[ETUM_DISC$ASISTE_CENTRO_EDUCATIVO == 1] <- "Si"
ETUM_DISC$ASISTE_CENTRO_EDUCATIVO[ETUM_DISC$ASISTE_CENTRO_EDUCATIVO == 2] <- "No"
ETUM_DISC$SABE_LEER_Y_ESCRIBIR[ETUM_DISC$SABE_LEER_Y_ESCRIBIR == 1] <- "Si"
ETUM_DISC$SABE_LEER_Y_ESCRIBIR[ETUM_DISC$SABE_LEER_Y_ESCRIBIR == 2] <- "No"
ETUM_DISC$PADECE_ENFERMEDAD_CRÓNICA[ETUM_DISC$PADECE_ENFERMEDAD_CRÓNICA == 1] <- "Si"
ETUM_DISC$PADECE_ENFERMEDAD_CRÓNICA[ETUM_DISC$PADECE_ENFERMEDAD_CRÓNICA == 2] <- "No"
ETUM_DISC$LIMITACIÓN_PARA_RELACIONARSE[ETUM_DISC$LIMITACIÓN_PARA_RELACIONARSE == 1] <- "Si"
ETUM_DISC$LIMITACIÓN_PARA_RELACIONARSE[ETUM_DISC$LIMITACIÓN_PARA_RELACIONARSE == 2] <- "No"
ETUM_DISC$LIMITACIÓN_COMPRENSIVA[ETUM_DISC$LIMITACIÓN_COMPRENSIVA == 1] <- "Si"
ETUM_DISC$LIMITACIÓN_COMPRENSIVA[ETUM_DISC$LIMITACIÓN_COMPRENSIVA == 2] <- "No"
ETUM_DISC$LIMITACIÓN_AUDITIVA[ETUM_DISC$LIMITACIÓN_AUDITIVA == 1] <- "Si"
ETUM_DISC$LIMITACIÓN_AUDITIVA[ETUM_DISC$LIMITACIÓN_AUDITIVA == 2] <- "No"
ETUM_DISC$LIMITACIÓN_COMUNICATIVA[ETUM_DISC$LIMITACIÓN_COMUNICATIVA == 1] <- "Si"
ETUM_DISC$LIMITACIÓN_COMUNICATIVA[ETUM_DISC$LIMITACIÓN_COMUNICATIVA == 2] <- "No"
ETUM_DISC$LIMITACIÓN_VISUAL[ETUM_DISC$LIMITACIÓN_VISUAL == 1] <- "Si"
ETUM_DISC$LIMITACIÓN_VISUAL[ETUM_DISC$LIMITACIÓN_VISUAL == 2] <- "No"
ETUM_DISC$LIMITACIÓN_PARA_MOVILIZARSE[ETUM_DISC$LIMITACIÓN_PARA_MOVILIZARSE == 1] <- "Si"
ETUM_DISC$LIMITACIÓN_PARA_MOVILIZARSE[ETUM_DISC$LIMITACIÓN_PARA_MOVILIZARSE == 2] <- "No"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 1] <- "Está trabajando"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 2] <- "Falta de dinero para pagar sus estudios"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 3] <- "No le interesa/no quiere"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 4] <- "El estudio es muy difícil"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 5] <- "La institución educativa queda muy lejos"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 6] <- "Los profesores son insensibles"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 7] <- "El local está en malas condiciones"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 8] <- "Inseguridad ciudadana"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 9] <- "No tiene quien lo lleve"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 10] <- "Problemas de transporte"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 11] <- "Enfermedad no relacionada con su limitación"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 12] <- "No lo aceptaron en la escuela"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 13] <- "La infraestructura del centro de estudios no es adecuada"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 14] <- "Maltrato físico"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 15] <- "Maltrato psicológico"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 16] <- "Los profesores no enseñan bien"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 17] <- "Concluyó sus estudios"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 18] <- "Ya no está en edad de estudiar"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 19] <- "Su limitación lo impide"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 20] <- "No existe un centro de estudios en la zona"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 21] <- "Otro"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 22] <- "No opina"
ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR[ETUM_DISC$NO_ASISTE_CENTRO_EDUCATIVO_POR == 99] <- "Sin respuesta"
ETUM_DISC <- ETUM_DISC[,-1:-2]


## BASE DE DATOS FINAL:
BD_TUMBES <- cbind(TUM_DISC, ETUM_DISC, HTUM_DISC, STUM_DISC)
write.csv(BD_TUMBES, "BD_TUMBES2.csv", fileEncoding = "UTF-8")

