library(readr)
library(plyr)
library(dplyr)
library(foreign)
Poblacion_Peru <- read_csv("CAP_500_EDUCACION.csv",col_types = "cccccccccnccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc")
BD_Tumbes <- filter(Poblacion_Peru,Poblacion_Peru$NOMBREDD == "TUMBES")
BD_Tumbes2 <- select(BD_Tumbes, 9:17, 21:21, P502, 46:47,50:52, P509, 72:75)

BD_Tumbes_PCD <- rename(BD_Tumbes2, SEXO = P105, EDAD = P106, LIMITACIÓN_PARA_MOVILIZARSE = P203, LIMITACIÓN_VISUAL = P204, LIMITACIÓN_COMUNICATIVA = P205, LIMITACIÓN_AUDITIVA = P206, LIMITACIÓN_COMPRENSIVA = P207, LIMITACIÓN_PARA_RELACIONARSE = P208, PADECE_ENFERMEDAD_CRÓNICA = P209, SABE_LEER_Y_ESCRIBIR = P501 ,ASISTE_CENTRO_EDUCATIVO = P502, PROFESORES_ESPECIALIZADOS = 'P508$1', COMPUTADORAS_ESPECIALIZADAS = 'P508$2',
LIBROS_BRAILE = 'P508$5', LIBROS_HABLADOS = 'P508$6', LENGUAJE_SEÑAS = 'P508$7', NO_ASISTE_CENTRO_EDUCATIVO_POR = P509, RAMPAS_ACCESO = 'P513_V1$1', BARANDAS_SEGURIDAD = 'P513_V1$2', ASCENSORES_ADECUADOS = 'P513_V1$3', SERVICIOS_HIGIENICOS_DISCAPACITADOS = 'P513_V1$4')
write.csv(BD_Tumbes_PCD, "BD_TUMBES_PCD.csv")